Repository freenas/freenas-docs, pull requests merged in 2019-09, with the labels that each got.

#1499 NAS-102540: Add description of Schedule Calendar behavior
  userguide/Makefile
  userguide/conf.py
  userguide/images/schedule_calendar.png
  userguide/intro.rst
  userguide/snippets/usingui.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1500 NAS-102739: Update 'Create Dataset' Share Type field behavior
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1501 NAS-102813: Rsync task status alerts
  userguide/intro.rst
  userguide/snippets/alertevents.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1502 NAS-102920: Add EULA button to TrueNAS Support section.
  userguide/images/truenas/system-support.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1503 NAS-102924: Update Jails/'Release' field description.
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1504 NAS-102946: Remove Amazon Cloud Drive credential option
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1505 NAS-102986: Remove help text toggle
  userguide/images/settings-preferences.png
  userguide/intro.rst
  userguide/settings.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1506 NAS-100391: iocage log file
  userguide/intro.rst
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1509 NAS-102156: Add Naming Schema field to manual snapshot create
  userguide/images/storage-snapshots-create.png
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1510 NAS-102850: Update SSH Keypairs text to indicate encrypted/passphrase…
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1493 NAS-102865 add ifdef for trunas and freenas about hot-swap drive bays
  userguide/storage.rst
Labels: 11.2-legacy, FN 11.2-U6, FN/TN

#1494 NAS-102865 add ifdef for trunas and freenas about hot-swap drive bays
  userguide/storage.rst
Labels: Angulargui, FN 11.2-U6, FN/TN

#1498 FreeNAS 11.2-U6 Screenshot review (legacy UI)
  userguide/images/esxi5a.png
  userguide/images/initial1c.png
  userguide/images/install2c.png
  userguide/images/jails10b.png
  userguide/images/jails11b.png
  userguide/images/jails3a.png
  userguide/images/jails9a.png
  userguide/images/plugins1b.png
  userguide/images/plugins2.png
  userguide/images/plugins3a.png
  userguide/images/plugins4.png
  userguide/images/plugins5.png
  userguide/images/ports1a.png
  userguide/images/ports2.png
  userguide/images/quick-login.png
  userguide/images/sharing-iscsi-extent-add.png
  userguide/images/sharing-smb-add.png
  userguide/images/system-alerts.png
  userguide/images/system-bootenv1a.png
  userguide/images/system-information.png
  userguide/images/tn_afp2a.png
  userguide/images/tn_be3b.png
  userguide/images/tn_cinder-admin-volsnaps.png
  userguide/images/tn_cinder-admin-voltypes-create.png
  userguide/images/tn_cinder-admin-voltypes.png
  userguide/images/tn_cinder-project-volsnaps.png
  userguide/images/tn_cinder_admin_sys_vols.png
  userguide/images/tn_cinder_project_compute_vols.png
  userguide/images/tn_services-afp.png
  userguide/images/tn_tftp.png
  userguide/images/tn_vcenter-datastore-clone.png
  userguide/images/tn_vcenter-datastore-config-nfs.png
  userguide/images/tn_vcenter-datastore-confirm-nfs.png
  userguide/images/tn_vcenter-datastore-confirm-vmfs.png
  userguide/images/tn_vcenter-datastore-create-hostselection.png
  userguide/images/tn_vcenter-datastore-extend.png
  userguide/images/tn_vcenter-datastore-vmfs-config.png
  userguide/images/tn_vcenter-extent-create.png
  userguide/images/tn_vcenter-new-periodic-snapshot.png
  userguide/images/tn_vcenter-newhost.png
  userguide/images/tn_vcenter-plugin-config.png
  userguide/images/tn_vcenter-plugin-secure.png
  userguide/images/tn_vcenter-replication-create.png
  userguide/images/tn_vcenter-snapshot-manage.png
  userguide/images/tn_vcenter-target-create.png
  userguide/images/tn_vcenter-target-edit.png
  userguide/images/tn_vcenter-zvol-create.png
  userguide/images/tn_vcenter-zvol-edit.png
  userguide/images/tn_view.png
  userguide/images/tn_volume2.png
  userguide/images/view.png
Labels: 11.2-legacy, FN 11.2-U6, FN/TN

#1496 11.2-U6 Screenshot update
  userguide/images/alert-example.png
  userguide/images/installer-install-menu.png
  userguide/images/truenas/cinder-admin-volsnaps.png
  userguide/images/truenas/cinder-admin-voltypes-create.png
  userguide/images/truenas/cinder-admin-voltypes.png
  userguide/images/truenas/cinder-project-volsnaps.png
  userguide/images/truenas/cinder_admin_sys_vols.png
  userguide/images/truenas/cinder_project_compute_vols.png
  userguide/images/truenas/vcenter-datastore-clone.png
  userguide/images/truenas/vcenter-datastore-config-nfs.png
  userguide/images/truenas/vcenter-datastore-confirm-nfs.png
  userguide/images/truenas/vcenter-datastore-confirm-vmfs.png
  userguide/images/truenas/vcenter-datastore-create-hostselection.png
  userguide/images/truenas/vcenter-datastore-extend.png
  userguide/images/truenas/vcenter-datastore-vmfs-config.png
  userguide/images/truenas/vcenter-extent-create.png
  userguide/images/truenas/vcenter-new-periodic-snapshot.png
  userguide/images/truenas/vcenter-newhost.png
  userguide/images/truenas/vcenter-plugin-config.png
  userguide/images/truenas/vcenter-plugin-secure.png
  userguide/images/truenas/vcenter-replication-create.png
  userguide/images/truenas/vcenter-snapshot-manage.png
  userguide/images/truenas/vcenter-target-create.png
  userguide/images/truenas/vcenter-target-edit.png
  userguide/images/truenas/vcenter-zvol-create.png
  userguide/images/truenas/vcenter-zvol-edit.png
  userguide/images/vmware-settings.png
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1518 Revert "NAS-102850: review update 1"
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1524 update replacing disk to grow a pool.
  userguide/storage.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1507 NAS-101146: Begin investigating Fibre Channel changes
  userguide/images/truenas/fibre1.png
  userguide/images/truenas/fibre4c.png
  userguide/images/truenas/system-tunables-npiv.png
Labels: 11.3 Beta 1, Angulargui, TrueNAS, don't merge yet

#1490 NAS-102301: Update tn_intro.rst
  userguide/intro.rst
  userguide/snippets/usingui.rst
  userguide/tn_intro.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1497 Rewrite 11.2-angular process for replacing encrypted disk.
  userguide/storage.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1511 NAS-101365: Update Jails networking subsection to include text and ca…
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1512 NAS-101816: Small update to CA/'Sign CSR' option description.
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1513 NAS-101816: Small update to CA/'Sign CSR' option description.
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1529 Review all screenshots for 11.2-U6 and update as needed
  userguide/images/dashboard.png
  userguide/images/network-ipmi.png
  userguide/images/save-config.png
  userguide/images/sharing-afp-dataset-permissions.png
  userguide/images/sharing-block-iscsi-authorized-access-example.png
  userguide/images/sharing-block-iscsi-initiators-example.png
  userguide/images/storage-disks-replace.png
  userguide/images/storage-disks-resilvered.png
  userguide/images/storage-pools-actions-detach.png
  userguide/images/storage-pools-import-no-encryption.png
  userguide/images/storage-pools-upgrade.png
  userguide/images/storage-pools-zvol-edit.png
  userguide/images/system-boot-environments.png
  userguide/images/system-certificates-manage.png
  userguide/images/system-manualupdate.png
  userguide/images/system-update.png
  userguide/images/tasks-replication-tasks-manual-complete.png
  userguide/images/tasks-replication-tasks-manual-key.png
  userguide/images/tasks-replication-tasks-semiauto-complete.png
  userguide/images/tasks-replication-tasks-semiauto-snapshot.png
  userguide/images/tasks-replication-tasks-semiauto-token.png
  userguide/images/tasks-replication-tasks-semiauto.png
  userguide/images/themes-selector.png
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1476 NAS-102656: Update 'Setting Permissions' section
  userguide/images/storage-pools-edit-permissions.png
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1516 NAS-100895: Update Network/LAGG + VLAN documentation
  userguide/images/network-link-aggregations-members-add.png
  userguide/images/network-link-aggregations-members.png
  userguide/network.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1525 NAS-102256: Update Bind IP Addresses description.
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1527 NAS-100746: TrueNAS Guide - Update System/Support to document the unified Support/Proactive Support pages.
  userguide/images/truenas/system-proactive-support.png
  userguide/images/truenas/system-support.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1492 NAS-102547 Intro entry for delay boot until VNC Connects location
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1495 NAS-102955 doc rsync path limit being 1023 characters.
  userguide/intro.rst
  userguide/snippets/pathlengths.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1469 NAS-102881 rework help text docs. doc'ed dragability of boxes
  userguide/Makefile
  userguide/conf.py
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1526 NAS-101293: Rename VFS modules to VFS objects:
  userguide/intro.rst
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1530 NAS-102924: Review update 1
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1531 NAS-102931: Rewrite 'Threshold days' description.
  userguide/snippets/usingui.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1533 NAS-103066: Update 'View Enclosure' section in TrueNAS guide.
  userguide/images/truenas/system-view-enclosure.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1535 NAS-103052: System/General - Update note about restarting web service
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1538 NAS-103033: Update manual snapshot procedure
  userguide/images/storage-snapshots-create.png
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1539 NAS-101146: Update iSCSI sharing Fibre Channel section
  userguide/images/truenas/fibre2.png
  userguide/images/truenas/fibre3.png
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1540 NAS-102739: Update from testing notes
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1541 Fix angulargui build warning
  userguide/intro.rst
Labels: Angulargui, FN/TN

#1522 NAS-103041 slight rewrite to displaying jail info in table
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1528 NAS-102699 doc detach and refresh button on pool status page.
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1532 NAS-102490 Update the hover highlighting functionality for tables
  userguide/_static/themes/trueos_style/static/css/trueos_style.css
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1544 Nas 102955 angulargui
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1534 NAS-103099: Document INITIATE FAILOVER button
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1523 NAS-102737 Rewrite of explanation of available/used space in pools.
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1543 NAS-101272: Review Advanced Replication Creation field descriptions
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1546 NAS-103016: Update Permissions Editor docs
  userguide/images/storage-pools-edit-permissions.png
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1547 NAS-103111: Update TrueNAS Support docs to mention reloading UI.
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1548 NAS-102368: Add 'Default ACL Options' to "ACL Options" table
  userguide/images/storage-acls.png
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1549 NAS-102879: Expand update in progress text
  userguide/conf.py
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1551 NAS-103035: Update SMART alert behavior
  userguide/images/services-smart.png
  userguide/intro.rst
  userguide/services.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1514 NAS-102450: Update 'WebGUI HTTP -> HTTPS Redirect' description.
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1554 NAS-100995: Unlock SED before including in pool
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1553 NAS-102996: Add nat_forwards field to docs
  userguide/intro.rst
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1556 NAS-103152 Remove docs for save config toggle.
  userguide/intro.rst
  userguide/settings.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1537 NAS-103089: Document 'Region' S3 Cloud Cred. field
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1560 NAS-103142 fix TN docs on going to userguide from UI
  userguide/support.rst
  userguide/truenas.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1561 NAS-101923 doc "Stream Compression" behavior for replicate tasks.
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1552 NAS-103183: Add "Advanced Scheduler" subsection
  userguide/images/custom-scheduler.png
  userguide/snippets/usingui.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1562 NAS-103231 doc language field changing to combo-box.
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1563 NAS-103188 doc new/removed fields in AD and LDAP
  userguide/directoryservices.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1565 NAS-102266: Update from Releng feedback
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1566 NAS-102266: Update from Releng feeback
  userguide/system.rst
Labels: 11.2-legacy, TrueNAS

#1545 NAS-102085: Rewrite Replication Wizard documentation
  userguide/conf.py
  userguide/images/tasks-replication-add-wizard-snapshots.png
  userguide/images/tasks-replication-add-wizard-ssh.png
  userguide/images/tasks-replication-add-wizard-step1.png
  userguide/images/tasks-replication-add-wizard-step2.png
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1568 NAS-103142 remove old docs about userguide for TN
  userguide/tn_options.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1567 NAS-103229 doc updated task manager
  userguide/taskmanager.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1571 NAS-103188 intro entry for new/removed AD,LDAP fields.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1558 NAS-102847 add docs on helptext in truenas UI
  userguide/Makefile
  userguide/conf.py
  userguide/snippets/typography.rst
  userguide/snippets/usingui.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1559 NAS-102416 slight rewrite/update to docs on extending pool
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN
