Repository freenas/freenas-docs, pull requests merged in 2019-01, with the labels that each got.

#532 Fixed a text issue where it was rendering incorrectly in HTML.
  userguide/storage.rst
Labels: FN/TN

#538 Add an example of creating VM. Further explains the 'Start to Boot' s…
  userguide/virtualmachines.rst
Labels: FN/TN

#523 65220: Update quasselcore to plex in Plugins/Delete section:
  userguide/plugins.rst
Labels: FN/TN

#465 ES60 BSG Changes: #57150
  userguide/snippets/contact.rst
  userguide/snippets/es60.rst
  userguide/snippets/userguide.rst
Labels: BSG

#511 (BSG change) 57339 : Update storage controller removal data loss warning.
  userguide/snippets/mseries.rst
Labels: BSG

#513 Replaced all expansion module references to official expansion controller term
  userguide/images/tn_es12_back.png
  userguide/images/tn_es24_back.png
  userguide/snippets/es12.rst
  userguide/snippets/es24.rst
  userguide/snippets/es60.rst
Labels: BSG

#524 Port PR 465 to master branch
  userguide/snippets/contact.rst
  userguide/snippets/es60.rst
  userguide/snippets/userguide.rst
Labels: BSG

#503 Updated text about adding spare to enctypted pool. Also added new sym…
  userguide/conf.py
  userguide/snippets/typography.rst
  userguide/storage.rst
Labels: FN/TN

#510 Add note about how plugins and jails are updated/upgraded
  userguide/plugins.rst
Labels: FN/TN

#512 Updated vnet_mac entries for networking options of jails.
  userguide/jails.rst
Labels: FN/TN

#516 Updated the install link for the latest version of FreeNAS.
  userguide/install.rst
Labels: FN/TN

#517 Updated install link for FreeNAS (angular).
  userguide/install.rst
Labels: FN/TN

#518 60192: Update caution about used space of a pool with iSCSI to 80%:
  userguide/sharing.rst
Labels: FN/TN

#519 Update caution about used space of a pool with iSCSI to 80%:
  userguide/sharing.rst
Labels: FN/TN

#535 Clarified the cloud sync scheduling function.
  userguide/tasks.rst
Labels: FN/TN

#520 Update Storage/Managing Encrypted Pools to better explain ZFS "full disk" encryption.
  userguide/storage.rst
Labels: FN/TN

#521 Update Storage/Managing Encrypted Pools to better explain ZFS "full d…
  userguide/storage.rst
Labels: FN/TN

#526 Removed the bit about using DD in Rufus.
  userguide/install.rst
Labels: FN/TN

#527 Removed the bit about DD when using Rufus (master branch).
  userguide/install.rst
Labels: FN/TN

#530 40596: initial review of NFS Sharing text:
  userguide/conf.py
  userguide/sharing.rst
  userguide/snippets/typography.rst
Labels: FN/TN

#531 Port changes from PR 530 (Sharing/NFS rework) to master branch:
  userguide/sharing.rst
Labels: FN/TN

#534 Added links that elaborate on SSL and TLS encryption (angulargui).
  userguide/directoryservices.rst
Labels: FN/TN

#536 Add warning about allowed characters in target names
  userguide/sharing.rst
Labels: FN/TN

#560 Add max. character limit to IPMI password field
  userguide/network.rst
Labels: FN/TN

#559 Port PR 558 (note about GELI passphrase on login) to angulargui
  userguide/system.rst
Labels: Angulargui, TrueNAS

#568 Fixed table. Ensured parity of info between master and 11.1-stable br…
  userguide/services.rst
Labels: freenas/11.1-stable

#572 65034: update proactive support image and review related text
  userguide/images/tn_system-proactive-support.png
  userguide/system.rst
Labels: Master, TrueNAS

#573 Synchronize PR 572 (proactive support image & text) with angulargui branch
  userguide/images/truenas/system-proactive-support.png
  userguide/system.rst
Labels: Angulargui, TrueNAS

#525 Add nfs pass-thru section to virtualmachines.rst:
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#528 Add WIP tip about configuring AD with two FreeNAS systems
  userguide/directoryservices.rst
Labels: Angulargui, FN/TN

#533 Added a link that explains TLS and SSL encryption.
  userguide/directoryservice.rst
Labels: FN/TN, Master

#547 Port PR 140 (update AFP and SMB sharing text) to updated master branch:
  userguide/sharing.rst
Labels: Master

#566 Port PR140 to angulargui branch:
  userguide/sharing.rst
Labels: Angulargui

#558 31656: Add note about GELI passphrase requirement at UI login.
  userguide/system.rst
Labels: Master, TrueNAS

#574 Add text about character restrictions for SMTP passwords.
  userguide/system.rst
Labels: Angulargui, FN/TN

#575 Sync PR 574 (SMTP passwords) with master:
  userguide/system.rst
Labels: FN/TN, Master

#546 Added note about cloud sync operation times (master).
  userguide/tasks.rst
Labels: Master

#578 56610: Include snippet about User Guide location in "Support Resources" chap…
  userguide/snippets/userguide.rst
  userguide/support.rst
Labels: Angulargui

#553 Added a warning that credentials are lost when key isn't preserved (11.1-stable).
  userguide/system.rst
Labels: freenas/11.1-stable

#555 Added warning that credentials are lost when key isn't preserved (master).
  userguide/system.rst
Labels: Master

#581 Update x-series unit sas wiring.
  userguide/images/tn_x_sas_wiring.png
Labels: BSG, Master

#582 Update x-series unit sas wiring.
  userguide/images/truenas/x_sas_wiring.png
Labels: Angulargui, BSG

#589 48941: Add warning about losing cloud creds.
  userguide/system.rst
Labels: Angulargui

#591 Update System/Information images for 11.1-U7
  userguide/images/initial1c.png
  userguide/images/system-information.png
Labels: freenas/11.1-stable

#592 Fix initial1c and system-information
  userguide/images/initial1c.png
  userguide/images/system-information.png
Labels: freenas/11.1-stable

#590 69382: Add correct freenas doc's link.
  userguide/snippets/userguide.rst
Labels: freenas/11.1-stable

#593 65247: Update text describing columns in Storage/Snapshots:
  userguide/storage.rst
Labels: Angulargui, FN/TN

#561 54954: document new "Enable SMB1 field"
  userguide/images/services-smb.png
  userguide/images/tn_cifs1b.png
  userguide/services.rst
Labels: FN/TN, Master

#564 54954: document new "Enable SMB1 field" (PR 561 cherry-pick)
  userguide/images/services-smb.png
  userguide/images/tn_cifs1b.png
  userguide/services.rst
Labels: freenas/11.1-stable

#600 68473: Add note about tap interfaces and virtual machines.
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#601 68473: Port PR600 to master branch:
  userguide/intro.rst
  userguide/vms.rst
Labels: FN/TN, Master

#597 60792: Port PR 596 and a few incidental changes
  userguide/directoryservice.rst
Labels: FN/TN, Master

#598 60792: Port PR596 to 11.1-stable
  userguide/directoryservice.rst
Labels: FN/TN, freenas/11.1-stable

#599 69382: Added ifdef statements for links to the guide.
  userguide/snippets/userguide.rst
Labels: Master

#608 69382: Updated guide section to include updated snippets section.
  userguide/help.rst
  userguide/snippets/userguide.rst
Labels: freenas/11.1-stable

#611 61107: Port PR610 to master branch
  userguide/storage.rst
Labels: FN/TN, Master

#612 61107: Port PR610 to freenas/11.1 branch
  userguide/storage.rst
Labels: FN/TN, freenas/11.1-stable

#607 69382: Updated guide section to include updated snippets section.
  userguide/es12.rst
  userguide/es24.rst
  userguide/es60.rst
  userguide/help.rst
  userguide/mseries.rst
  userguide/snippets/es12.rst
  userguide/snippets/es24.rst
  userguide/snippets/es60.rst
  userguide/snippets/mseries.rst
  userguide/snippets/userguide.rst
  userguide/snippets/xseries.rst
  userguide/xseries.rst
Labels: Master

#609 56013: Add "Enable SMB1 support" text to angulargui branch.
  userguide/services.rst
Labels: Angulargui, FN/TN

#610 61107: Add text about promote dataset option to zvol configuration section
  userguide/storage.rst
Labels: Angulargui, FN/TN

#621 Copyright year substitution:
  userguide/conf.py
  userguide/intro.rst
  userguide/snippets/copyright.rst
  userguide/tn_intro.rst
Labels: FN/TN, Master

#617 71121: Update manual volume creation text
  userguide/images/manual.png
  userguide/storage.rst
Labels: FN/TN, freenas/11.1-stable

#618 71121: Port PR 617 (manual volume creation) to [master]
  userguide/images/manual.png
  userguide/storage.rst
Labels: FN/TN, Master

#614 Update copyright year.
  userguide/conf.py
  userguide/intro.rst
  userguide/snippets/copyright.rst
  userguide/tn_intro.rst
Labels: Angulargui, FN/TN

#594 59397: Add entry to intro.rst about new column.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#595 59397: Update entry for Domain Account Password in directoryservices.rst
  userguide/directoryservices.rst
  userguide/intro.rst
Labels: Angulargui, FN/TN

#596 60792: Update Certificate field in directoryservices.rst/AD section
  userguide/directoryservices.rst
Labels: Angulargui, FN/TN

#606 54747: Add "critical for failover" configuration reference in network…
  userguide/network.rst
  userguide/snippets/console_menu.rst
Labels: Master, TrueNAS

#613 52607: Add text for new browse option in Tasks/Cloud Sync tasks/Add.
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#615 Update copyright year
  userguide/conf.py
  userguide/intro.rst
  userguide/snippets/copyright.rst
  userguide/tn_intro.rst
Labels: FN/TN, freenas/11.1-stable

#616 61866: Updated table to match new field labels.
  userguide/virtualmachines.rst
Labels: Angulargui

#619 Made 'Alert Settings' into refs.
  userguide/snippets/alertevents.rst
Labels: Angulargui, FN/TN

#627 61188: Added info to hot spares section on how to add spare devices.
  userguide/storage.rst
Labels: FN/TN, Master

#628 Fix building TrueNAS guide
  userguide/directoryservices.rst
  userguide/system.rst
  userguide/truenas.rst
Labels: Angulargui, TrueNAS

#631 Add entry reflecting l2arc size reporting change to intro.
  userguide/intro.rst
Labels: FN/TN, Master

#633 58083: Updated TLS vs SSL.
  userguide/directoryservices.rst
Labels: Angulargui, FN/TN

#625 Port PR623 (bug submit text) to 11.1-stable branch.
  userguide/system.rst
Labels: FN/TN, freenas/11.1-stable

#623 53622: improve bug submission text
  userguide/system.rst
Labels: Angulargui, FN/TN

#637 32793: Update reporting/ZFS section to reflect each graph.
  userguide/reporting.rst
Labels: FN/TN, Master

#638 32793: Retest and port PR637 (reporting.rst update) to angulargui.
  userguide/reporting.rst
Labels: Angulargui, FN/TN

#640 67618: update SMTP password text
  userguide/system.rst
Labels: FN/TN, Master

#641 67618: port PR 640 (SMTP password text) to angulargui
  userguide/system.rst
Labels: Angulargui, FN/TN

#644 FreeNAS Forum suggestion: Add example of exiting iocage jail console
  userguide/jails.rst
Labels: Angulargui, FN/TN

#639 56538: Added section on swap memory.
  userguide/storage.rst
Labels: Angulargui, FN/TN

#605 62880, 65139, 68923, 62712, and 67420: Update VM options buttons and review most of virtualmachines.rst
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#624 53622: Port PR 623 (bug submit text) to master.
  userguide/system.rst
Labels: FN/TN, Master

#648 33141: cherry pick PR647 (removed collectd IPMI plugin) to master.
  userguide/intro.rst
Labels: FN/TN, Master

#636 71699: Added entry on simpler plugin post_install
  userguide/plugins.rst
Labels: Angulargui, FN/TN

#649 66925: Add minimum bit lengths to CA and Certificate Private Key entries
  userguide/system.rst
Labels: Angulargui, FN/TN

#650 66925: Port PR 649 (minimum CA/Cert key bit lengths) to master
  userguide/system.rst
Labels: FN/TN, Master

#651 64728: Update pool available space description
  userguide/storage.rst
Labels: Angulargui, FN/TN

#652 53638: Add entry to intro to note pool widgets in dashboard change colors
  userguide/intro.rst
Labels: Angulargui, FN/TN

#653 62712: Update text and description for vm boot delay for vnc option
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#646 63483: Document new S3 Credential checkboxes (master)
  userguide/intro.rst
  userguide/system.rst
Labels: FN/TN, Master

#642 60138: Remove obsolete vCenter plugin documentation:
  userguide/tn_vcenter.rst
Labels: Master, TrueNAS

#643 60138: Port PR 642 (vcenter plugin text removal) to angulargui
  userguide/tn_vcenter.rst
Labels: Angulargui, TrueNAS

#647 33141: Add entry to intro about the removed collectd IPMI plugin.
  userguide/intro.rst
Labels: Angulargui, FN/TN
