Repository freenas/freenas-docs, pull requests merged in 2019-04, with the labels that each got.

#734 27736 (1.4 BSGs): Add hot spare drive identify behavior to TrueNAS guide:
  userguide/snippets/es24m_drivetrays.rst
  userguide/snippets/es60.rst
  userguide/snippets/x_drivetrays.rst
Labels: BSG, Master, Ready to Merge, TrueNAS

#796 78519: Update ES60 BSG CMA instructions
  userguide/snippets/es60.rst
Labels: BSG, Master

#802 Alphabetize and add descrips for replacement commands.
  userguide/Makefile
  userguide/conf.py
Labels: Angulargui

#806 Cherry-pick menuselection arrow fix to master
  userguide/Makefile
  userguide/conf.py
Labels: Master

#805 Fix broken arrow replacement for |menuselection|
  userguide/Makefile
  userguide/conf.py
Labels: Angulargui

#789 Doc Queue #58: Add note to vmware instructions about configuring jail networking
  userguide/install.rst
Labels: FN/TN, Master

#800 NAS-100952 Add Administrators Group field to Services/SMB documentation.
  userguide/images/services-smb.png
  userguide/intro.rst
  userguide/services.rst
Labels: 11.2-legacy, FN/TN

#803 Alphabetize and add descrips to replacement commands.
  userguide/Makefile
  userguide/conf.py
Labels: 11.2-angular

#811 Remove commented section to resync branches.
  userguide/intro.rst
Labels: Master

#812 NAS-100004 Add change note to intro and text about new IPMI event ale…
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: FN/TN, Master

#813 NAS-100004 Add change note to intro and text about new IPMI event ale…
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: Angulargui, FN/TN

#797 NAS-101353 Update docs for new pool status symbols.
  userguide/storage.rst
Labels: Angulargui, FN/TN

#801 NAS-101353 Update docs for new pool status symbols.
  userguide/storage.rst
Labels: 11.2-angular, FN/TN

#818 11.2U4: Update VFS Module descriptions
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN

#819 11.2U4: Update VFS Module descriptions
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#822 NAS-100140: Add "Bandwidth limit" field to Cloud Sync Options
  userguide/intro.rst
  userguide/tasks.rst
Labels: FN/TN, Master

#823 NAS-100390: Add Bandwidth Limit field to Cloud Sync Options
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#816 NAS-101056 Fix text that was referring to USB devices other than for install only.
  userguide/conf.py
  userguide/install.rst
  userguide/intro.rst
  userguide/reporting.rst
  userguide/sharing.rst
  userguide/system.rst
Labels: FN/TN, Master

#843 NAS-101056 update mentions of USB devices and boot devices.
  userguide/conf.py
  userguide/install.rst
  userguide/intro.rst
  userguide/reporting.rst
  userguide/sharing.rst
  userguide/system.rst
Labels: 11.2-legacy, FN/TN

#844 NAS-101056 Fix text that was referring to USB devices other than for install only.
  userguide/conf.py
  userguide/install.rst
  userguide/intro.rst
  userguide/reporting.rst
  userguide/sharing.rst
  userguide/system.rst
Labels: Angulargui, FN/TN

#846 NAS-101056 Fix text that was referring to USB devices other than for install only.
  userguide/conf.py
  userguide/install.rst
  userguide/intro.rst
  userguide/reporting.rst
  userguide/system.rst
Labels: 11.2-angular, FN/TN

#788 Doc Queue #58: Add note to vmware instructions about configuring jail networking
  userguide/install.rst
Labels: Angulargui, FN/TN, Ready to Merge

#798 NAS-100538 : Rework "SMB Share Options" table to indicate "global" is…
  userguide/sharing.rst
Labels: Angulargui, FN/TN, Ready to Merge

#799 NAS-100538 : Rework "SMB Share Options" table to indicate "global" is…
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN, Ready to Merge

#804 NAS-101187: Update guidance about moving the system dataset to an enc…
  userguide/system.rst
Labels: 11.2-legacy, FN/TN, Ready to Merge

#808 Fix broken arrow replacement for |menuselection|
  userguide/Makefile
Labels: 11.2-angular, bug

#814 NAS-100097: Update "Show Text Console without Password Prompt" descri…
  userguide/system.rst
Labels: FN/TN, Master, Ready to Merge

#815 NAS-100097: Update "Show Text Console without Password Prompt" description
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready to Merge

#824 Work with Support to refine SED documentation
  userguide/storage.rst
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready to Merge

#825 Work with Support to refine SED documentation.
  userguide/system.rst
Labels: 11.2-angular, FN/TN, Ready to Merge

#828 Work with Support to refine SED docs
  userguide/system.rst
Labels: FN/TN, Master, Ready to Merge

#829 Work with Support to refine SED docs
  userguide/system.rst
Labels: 11.2-legacy, FN/TN, Ready to Merge

#832 NAS-100270: Update encryption text to note the passphrase is needed t…
  userguide/storage.rst
Labels: FN/TN, Master

#834 NAS-100709: Update encrypted pool lock/unlock descriptions to note th…
  userguide/storage.rst
Labels: Angulargui, FN/TN

#830 NAS-100195: Add descriptions for new MTU fields in Network Interfaces and Link Ag…
  userguide/intro.rst
  userguide/network.rst
Labels: FN/TN, Master, Ready to Merge

#835 NAS-100313: Remove "Dos charset" field from Services/SMB docs.
  userguide/intro.rst
  userguide/services.rst
Labels: FN/TN, Master

#836 NAS-100825: Remove DOS Charset field from Global SMB Config Options t…
  userguide/intro.rst
  userguide/services.rst
Labels: Angulargui, FN/TN

#837 NAS-100317: Add "Use --fast-list" field description to Cloud Sync Options table
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#841 NAS-100370: Add "Organizational Unit" fields to CAs and Certificates …
  userguide/intro.rst
  userguide/system.rst
Labels: FN/TN, Master

#842 NAS-100536: Add "Organizational Unit" field to "CAs" and "Certificate…
  userguide/intro.rst
  userguide/system.rst
Labels: Angulargui, FN/TN

#851 NAS-100014: Add NFS Stats graph to reporting.
  userguide/images/reporting3.png
  userguide/intro.rst
  userguide/reporting.rst
Labels: FN/TN, Master

#873 Add info and link for Zenoss and ZenPack.
  userguide/services.rst
Labels: FN/TN, Master

#876 Add info and link for Zenoss and ZenPack.
  userguide/services.rst
Labels: Angulargui, FN/TN

#874 Add info and link for Zenoss and ZenPack.
  userguide/services.rst
Labels: 11.2-legacy, FN/TN

#875 Add info and link for Zenoss and ZenPack.
  userguide/services.rst
Labels: 11.2-angular, FN/TN

#786 Doc queue #56: expand description of a few VFS modules
  userguide/sharing.rst
Labels: Angulargui, FN/TN, Ready to Merge

#787 Doc queue #56: expand description of a few VFS modules
  userguide/sharing.rst
Labels: FN/TN, Master, Ready to Merge

#845 NAS-100393: Add text explaining system virtualization error.
  userguide/vms.rst
Labels: FN/TN, Master, Ready to Merge

#847 NAS-100393: Add text explaining system virtualization error.
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN, Ready to Merge

#848 NAS-100376: Add "Exclude" to Cloud Sync Options table
  userguide/intro.rst
  userguide/tasks.rst
Labels: FN/TN, Master, Ready to Merge

#850 NAS-100394: Add "Exclude" to Cloud Sync Options table
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN, Ready to Merge

#854 (Redmine) 73270: Add Snapshot retention policy fields and description…
  userguide/intro.rst
  userguide/storage.rst
Labels: FN/TN, Master, Ready to Merge

#861 NAS-101122: Update description of "Browsable to Network Clients" in S…
  userguide/sharing.rst
Labels: FN/TN, Master

#862 NAS-101122: Update description of "Browsable to Network Clients" in S…
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#863 NAS-101122: Update description of "Browsable to Network Clients" in S…
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#864 NAS-101122: Update description of "Browsable to Network Clients" in S…
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN

#826 NAS-100155 Add section and docs for new task manager in GUI.
  userguide/Makefile
  userguide/conf.py
  userguide/freenas.rst
  userguide/taskmanager.rst
Labels: Angulargui, FN/TN

#838 NAS-100350 Added docs for new fields in Cloud Sync Tasks > Add
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#840 NAS-100205 Added docs for new fields in Cloud Sync Tasks > Add.
  userguide/tasks.rst
Labels: FN/TN, Master

#849 NAS-100400 Add descrip of 'Host Sync' in UPS configuration table.
  userguide/services.rst
Labels: FN/TN, Master

#856 NAS-100478: Add entry for new zettarepl tool.
  userguide/intro.rst
Labels: FN/TN, Master

#857 NAS-100478: Add entry for new zettarepl tool.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#860 NAS-100504: Add one-shot critical alert icon and description
  userguide/Makefile
  userguide/conf.py
  userguide/snippets/alertevents.rst
Labels: Angulargui, FN/TN

#869 SED section: Work mav's comments into SED specs list.
  userguide/system.rst
Labels: FN/TN, Master, Ready to Merge

#870 SED section: Work mav's comments into SED specs list.
  userguide/system.rst
Labels: 11.2-legacy, FN/TN, Ready to Merge

#871 SED section: Work mav's comments into SED specs list.
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready to Merge

#872 SED section: Work mav's comments into SED specs list.
  userguide/system.rst
Labels: 11.2-angular, FN/TN, Ready to Merge

#879 Fix the cherry-pick mess for master branch (USB device stuff).
  userguide/install.rst
  userguide/intro.rst
  userguide/sharing.rst
Labels: FN/TN, Master

#881 Fix cherry-pick mess for angulargui branch (USB device stuff).
  userguide/sharing.rst
  userguide/system.rst
Labels: Angulargui, FN/TN

#882 Fix cherry-pick mess for 11.2-angular branch (USB device stuff).
  userguide/system.rst
Labels: 11.2-angular, FN/TN

#880 Fix cherry-pick mess for 11.2-legacy branch (USB device stuff).
  userguide/install.rst
  userguide/intro.rst
  userguide/sharing.rst
  userguide/system.rst
Labels: 11.2-legacy, FN/TN

#884 NAS-100468: Add "Transfers" to Cloud Sync Options table
  userguide/images/tasks-cloudsync.png
  userguide/intro.rst
  userguide/tasks.rst
Labels: FN/TN, Master

#855 NAS-100463 Added text for upgrading a plugin through UI.
  userguide/plugins.rst
Labels: Angulargui, FN/TN

#894 Update ESXi section for master branch.
  userguide/images/esxi-add-disk.png
  userguide/images/esxi1a.png
  userguide/images/esxi2a.png
  userguide/images/esxi3a.png
  userguide/images/esxi4a.png
  userguide/images/esxi5a.png
  userguide/images/esxi6a.png
  userguide/images/esxi_create_type.png
  userguide/images/esxi_custom_settings.png
  userguide/images/esxi_name_os.png
  userguide/images/esxi_ready_complete.png
  userguide/images/esxi_select_storage.png
  userguide/install.rst
Labels: FN/TN, Master

#885 NAS-100607: Add "Transfers" to Cloud Sync Options table:
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#883 NAS-100558: Add autodetect field to import disk options.
  userguide/images/storage-import.png
  userguide/intro.rst
  userguide/storage.rst
Labels: FN/TN, Master

#886 NAS-100229: Add "All Disks" field to SMART Test Options table:
  userguide/images/tasks-smart.png
  userguide/intro.rst
  userguide/tasks.rst
Labels: FN/TN, Master

#887 NAS-100611: Add "All Disks" field to SMART Test Options table:
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#866 NAS-101129: Rework SMB share connection example/instructions.
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN

#891 NAS-100662: Add "Follow symlinks" checkbox to Cloud Sync Options table
  userguide/intro.rst
  userguide/tasks.rst
Labels: FN/TN, Master

#892 NAS-100685: Add "Follow Symlinks" checkbox to Cloud Sync Options table
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#867 NAS-101129: Rework SMB share connection example/instructions.
  userguide/sharing.rst
Labels: FN/TN, Master, Ready to Merge

#865 NAS-101129: Rework SMB share connection example/instructions.
  userguide/sharing.rst
Labels: Angulargui, FN/TN, Ready to Merge

#868 NAS-101129: Rework SMB share connection example/instructions.
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN, Ready to Merge

#931 Fix description error for "Pool Available Space Threshold" field in "…
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN

#932 Fix description error for "Pool Available Space Threshold" field in "…
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#933 Fix description error for "Pool Available Space Threshold" field in "…
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#934 Fix description error for "Pool Available Space Threshold" field in "…
  userguide/sharing.rst
Labels: FN/TN, Master

#940 Update Account/Username field description.
  userguide/accounts.rst
Labels: Angulargui, FN/TN

#941 Update Account/Username field description.
  userguide/accounts.rst
Labels: 11.2-angular, FN/TN

#942 Update Account/Username field description.
  userguide/account.rst
Labels: FN/TN, Master

#943 Update Account/Username field description.
  userguide/account.rst
Labels: 11.2-legacy, FN/TN

#927 NAS-101129: sync with other PRs
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN, Ready to Merge

#890 NAS-101454 Add docs for the field change "Interface name" -> "Description".
  userguide/intro.rst
  userguide/network.rst
Labels: Angulargui, FN/TN

#896 NAS-101187: Update guidance about moving the system dataset to an encypted volume.
  userguide/system.rst
Labels: 11.2-angular, FN/TN

#897 NAS-101187: Update guidance about moving the system dataset to an encrypted volume.
  userguide/system.rst
Labels: Angulargui, FN/TN

#898 NAS-101187: Update guidance about moving the system dataset to an encrypted volume.
  userguide/system.rst
Labels: FN/TN, Master

#899 Update esxi 11.2legacy
  userguide/images/esxi-add-disk.png
  userguide/images/esxi1a.png
  userguide/images/esxi2a.png
  userguide/images/esxi3a.png
  userguide/images/esxi4a.png
  userguide/images/esxi5a.png
  userguide/images/esxi6a.png
  userguide/images/esxi_create_type.png
  userguide/images/esxi_custom_settings.png
  userguide/images/esxi_name_os.png
  userguide/images/esxi_ready_complete.png
  userguide/images/esxi_select_storage.png
  userguide/install.rst
Labels: 11.2-legacy, FN/TN

#900 Updated text and screenshots for the ESXi section.
  userguide/images/esxi-add-disk.png
  userguide/images/esxi_create_type.png
  userguide/images/esxi_custom_settings.png
  userguide/images/esxi_name_os.png
  userguide/images/esxi_ready_complete.png
  userguide/images/esxi_select_storage.png
  userguide/images/vmware-configuration.png
  userguide/images/vmware-create-os-disk.png
  userguide/images/vmware-create-storage-disk.png
  userguide/images/vmware-operating-system.png
  userguide/images/vmware-settings.png
  userguide/images/vmware-storage.png
  userguide/install.rst
Labels: 11.2-angular, FN/TN

#901 NAS-100952: Add Administrators Group field to Services/SMB documentation
  userguide/images/services-smb.png
  userguide/intro.rst
  userguide/services.rst
Labels: FN/TN, Master

#902 NAS-100952: Update SMB Services/Administrator Groups field name
  userguide/services.rst
Labels: 11.2-legacy, FN/TN

#903 NAS-100724: Update NetBIOS Alias description in Global SMB Configuration Options table
  userguide/services.rst
Labels: Angulargui, FN/TN

#904 NAS-100724: Update NetBIOS Alias description in Global SMB Configuration Options table
  userguide/services.rst
Labels: FN/TN, Master

#908 NAS-100823: Update Pool Status screen text to include scrub "Time Rem…
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN

#910 NAS-100848: Add NUT IPv6 listen change to intro
  userguide/intro.rst
Labels: FN/TN, Master

#911 NAS-100848: Add NUT IPv6 listen change to intro
  userguide/intro.rst
Labels: Angulargui, FN/TN

#914 73650: Adjust "Access Based Share Enumeration" field description in S…
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#915 73650: Adjust "Access Based Share Enumeration" field description in S…
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN

#916 73650: Adjust "Access Based Share Enumeration" field description in S…
  userguide/sharing.rst
Labels: FN/TN, Master

#917 73650: Adjust "Access Based Share Enumeration" field description in S…
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#921 NAS-101054: Remove Domain Controller Service from guide
  userguide/directoryservice.rst
  userguide/images/services-domain-controller.png
  userguide/intro.rst
  userguide/services.rst
Labels: FN/TN, Master

#922 NAS-101157: Remove Domain Controller from services.rst
  userguide/directoryservices.rst
  userguide/images/services-domain-controller.png
  userguide/intro.rst
  userguide/services.rst
Labels: Angulargui, FN/TN

#928 NAS-101096: Update "Path" description in "WebDAV Share Options" table
  userguide/sharing.rst
Labels: FN/TN, Master

#929 NAS-101096: Update "Path" Description in "WebDAV Share Options" table
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#939 NAS-100056: Add "Schedule" field description to "Replication Task Opt…
  userguide/intro.rst
  userguide/storage.rst
Labels: FN/TN, Master

#944 NAS-101203: Update "Extra Users" field name and description in UPS Co…
  userguide/services.rst
Labels: Angulargui, FN/TN

#945 NAS-101203: Update "Extra Users" field name and description in UPS Co…
  userguide/services.rst
Labels: 11.2-angular, FN/TN

#912 NAS-100853: Add "Name" field to Replication Task Options table
  userguide/intro.rst
  userguide/storage.rst
Labels: FN/TN, Master, Ready but conflicted

#913 NAS-100921: Add "Timeout" to Init/Shutdown Command or Script Options …
  userguide/images/tasks-initshutdown.png
  userguide/intro.rst
  userguide/tasks.rst
Labels: FN/TN, Master, Ready but conflicted

#918 NAS-100937: Add "Timeout" to Init/Shutdown Command or Script Options …
  userguide/intro.rst
  userguide/tasks.rst
Labels: Angulargui, FN/TN, Ready but conflicted

#930 NAS-100118: Add "System Clock" field to "VM Options" table
  userguide/images/vms-add.png
  userguide/intro.rst
  userguide/vms.rst
Labels: FN/TN, Master, Ready but conflicted

#935 NAS-101022: Remove maxqueuelen default sysctl from system.rst
  userguide/intro.rst
  userguide/system.rst
Labels: FN/TN, Master, Ready but conflicted

#936 NAS-101022: Remove maxqueuelen default sysctl from system.rst
  userguide/intro.rst
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready but conflicted

#852 NAS-100338 Added information about the 'VERIFY CREDENTIAL' button.
  userguide/system.rst
Labels: FN/TN, Master

#937 Add docs for the 'UNAVAIL' status of a pools.
  userguide/conf.py
  userguide/storage.rst
Labels: Angulargui, FN/TN

#938 Add docs for the 'UNAVAIL' status of a pools.
  userguide/conf.py
  userguide/storage.rst
Labels: 11.2-angular, FN/TN

#831 NAS-100260 Updated intro to include the new quota exceeded on dataset option.
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN

#833 NAS-100260 Updated intro to include the new quota exceeded on dataset option.
  userguide/intro.rst
  userguide/storage.rst
Labels: FN/TN, Master

#853 NAS-100461 Added information about the 'VERIFY CREDENTIAL' button.
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready to Merge

#859 NAS-100550 Added intructions for creating template jail through UI. Added entry to jail custom prop table.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#907 Add to intro about 3 new fields in Cloud Sync Tasks > ADD.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#909 Add to intro the 3 new fields in Cloud Sync Tasks > ADD.
  userguide/intro.rst
Labels: FN/TN, Master

#946 NAS-101371 Add a link to point to the "Update" section.
  userguide/install.rst
Labels: FN/TN, Master

#947 NAS-101371 Add a link to point to the "Update" section.
  userguide/install.rst
Labels: 11.2-legacy, FN/TN

#948 NAS-101371 Add a link to point to the "Update" section.
  userguide/install.rst
Labels: 11.2-angular, FN/TN

#949 NAS-101371 Add a link to point to the "Update" section.
  userguide/install.rst
Labels: Angulargui, FN/TN

#895 NAS-100695: Add Samba user quota administration text
  userguide/sharing.rst
Labels: FN/TN, Master, Ready to Merge

#954 NAS-100695: Add Samba user quota administration text
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#951 NAS-101203: Update "Extra users" description in UPS Config Options ta…
  userguide/services.rst
Labels: 11.2-legacy, FN/TN

#950 NAS-101203: Update "Extra users" description in UPS Config Options ta…
  userguide/services.rst
Labels: FN/TN, Master

#955 NAS-100955 Updated the "From Email" field descrip. to match the updated tool tip."
  userguide/system.rst
Labels: FN/TN, Master

#956 Updated the "From Email" field descrip. to match the updated tool tip."
  userguide/system.rst
Labels: 11.2-legacy, FN/TN

#957 Updated the "From Email" field descrip. to match the updated tool tip."
  userguide/system.rst
Labels: 11.2-angular, FN/TN

#959 Updated the "From Email" field descrip. to match the updated tool tip."
  userguide/system.rst
Labels: Angulargui, FN/TN

#960 Mention the new "VERIFY CREDENTIAL" button in the intro.
  userguide/intro.rst
Labels: FN/TN, Master

#961 Mention the new "VERIFY CREDENTIAL" button in the intro.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#952 NAS-100811: Rework jail update/upgrade and plugin update/upgrade sections:
  userguide/images/plugins-update.png
  userguide/intro.rst
  userguide/jails.rst
  userguide/plugins.rst
Labels: Angulargui, FN/TN

#953 NAS-100811: Rework jail update/upgrade and plugin update/upgrade sections:
  userguide/images/plugins-update.png
  userguide/intro.rst
  userguide/jails.rst
  userguide/plugins.rst
Labels: 11.2-angular, FN/TN

#919 NAS-100947 Add docs for "Enable Shadow Copies" checkbox.
  userguide/intro.rst
  userguide/sharing.rst
Labels: FN/TN, Master

#962 Mentioned template jail creation in the intro.
  userguide/intro.rst
Labels: Angulargui, FN/TN
