Repository freenas/freenas-docs, pull requests merged in 2019-02, with the labels that each got.

#669 45398: Add syslog-ng alert
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: Angulargui, FN/TN

#670 45398: Add syslog-ng alert
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: FN/TN, Master

#667 30495: Add entry to intro about new ability to pin help text.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#671 Doc Queue Item 1: Add AHCI disk recommendation for VMs with a Windows OS
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#672 Doc Queue Item 1: Add AHCI disk recommendation for VMs with a Windows OS
  userguide/vms.rst
Labels: FN/TN, Master

#673 67420: Port Docker VM text improvements to master
  userguide/vms.rst
Labels: FN/TN, Master, Ready to Merge

#645 63483: Document new Amazon S3 credential fields:
  userguide/intro.rst
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready to Merge

#475 Clarify purpose of encryption and disposal of disks
  userguide/storage.rst
Labels: FN/TN, Master

#661 56340 and 69195: Add new fields and fix field names in the "Advanced Jail Creation" tables:
  userguide/intro.rst
  userguide/jails.rst
Labels: Angulargui, FN/TN, Ready to Merge

#668 72991: Added screenshot. Fixed passive language. Moved note. All for asigra.
  userguide/images/services-asigra.png
  userguide/services.rst
Labels: FN/TN, Master

#660 71022: Add info for rolling back any snapshot.
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN

#680 Port PR #472 to angulargui (clarify Port field when selecting snmp dr…
  userguide/services.rst
Labels: Angulargui, FN/TN

#655 67420: Remove VM card references in Docker sections of virtualmachines.rst
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN, Ready to Merge

#657 63234: Doc new Advanced Plugin Installation option
  userguide/intro.rst
  userguide/plugins.rst
Labels: Angulargui, FN/TN, Ready to Merge

#664 25705: Add text about downloading updates from a secure source
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready to Merge

#665 25705: Add text about downloading updates from a secure source
  userguide/system.rst
Labels: FN/TN, Master, Ready to Merge

#666 50321: Add text about new NAA column in Sharing/iSCSI/Extents:
  userguide/intro.rst
  userguide/sharing.rst
Labels: Angulargui, FN/TN, Ready to Merge

#674 Doc queue item 77: FreeNAS forum: Clarify initial SED password
  userguide/system.rst
Labels: Angulargui, FN/TN, Ready to Merge

#675 Doc Queue item 77: FreeNAS forum: Clarify initial SED password
  userguide/system.rst
Labels: FN/TN, Master, Ready to Merge

#684 72459: Fix minor typo in system.rst/Cloud Credential Options table.
  userguide/system.rst
Labels: FN/TN, Master

#685 72459: Fix minor typo in Cloud Credential Options table
  userguide/system.rst
Labels: Angulargui, Master

#686 59973: Add entry to intro.rst for new "Reboot After Update" field.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#683 62361: Update default_vnet_interface descrip.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#682 Doc queue item 31: Add note about Windows disabling SMB2 guest access.
  userguide/sharing.rst
Labels: FN/TN, Master

#687 62712: Add entry to intro.rst for rename of VNC "Wait to Boot" option.
  userguide/intro.rst
Labels: Angulargui, FN/TN, Ready to Merge

#681 Doc queue item 31: Add note about SMB2 guest access disabled in Windows.
  userguide/sharing.rst
Labels: Angulargui, FN/TN, Ready to Merge

#690 Doc queue item 3: Add and rework cinder driver instructions:
  userguide/cinder.rst
  userguide/freenas.rst
Labels: FN/TN, Master, don't merge yet

#694 73191: services.rst: Add text about listing multiple domains for Dynamic DNS
  userguide/services.rst
Labels: FN/TN, Master

#695 73191: Add text about listing multiple domains for Dynamic DNS
  userguide/services.rst
Labels: Angulargui, FN/TN

#696 Sync cinder docs changes
  userguide/cinder.rst
  userguide/freenas.rst
  userguide/tn_cinder.rst
Labels: Angulargui, FN/TN

#678 68835: Document new Time Machine option for SMB shares.
  userguide/intro.rst
  userguide/sharing.rst
Labels: FN/TN, Master, Ready to Merge

#677 68430: Document new Time Machine checkbox for SMB shares
  userguide/intro.rst
  userguide/sharing.rst
Labels: Angulargui, FN/TN, Ready to Merge

#688 Fixed link to the alert section in bsgs.
  userguide/snippets/es12.rst
  userguide/snippets/es24.rst
  userguide/snippets/es60.rst
  userguide/snippets/mseries.rst
  userguide/snippets/xseries.rst
Labels: BSG, Master

#689 Doc Queue item 4: Add text about PCRE regex support to filter disks.
  userguide/storage.rst
Labels: Angulargui, FN/TN, Ready to Merge

#692 Update text on editing running jails. Read-only when running.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#697 Update all needed manual screenshots for 11.2-U2.
  userguide/images/alert-example.png
  userguide/images/installer-install-menu.png
  userguide/images/network-link-aggregations-edit.png
  userguide/images/network-link-aggregations-members-add.png
  userguide/images/network-link-aggregations-members.png
  userguide/images/storage-pools-encrypt-passphrase.png
  userguide/images/system-boot-mirror.png
  userguide/images/system-update.png
Labels: Angulargui, FN/TN

#698 Update install2c.png for 11.2-U2:
  userguide/images/install2c.png
Labels: FN/TN, Master

#700 master: Updated add windows (smb) screenshot.
  userguide/images/cifs2a.png
  userguide/images/sharing-smb-add.png
  userguide/sharing.rst
Labels: FN/TN, Master

#701 Rework vCenter doc to reflect WIP status
  userguide/tn_vcenter.rst
Labels: Angulargui, FN/TN

#691 Remove usage of 'Detach' from guide. Button changed name.
  userguide/storage.rst
Labels: Angulargui, FN/TN, Ready to Merge

#702 Rework vCenter doc to reflect the plugin WIP status.
  userguide/tn_vcenter.rst
Labels: FN/TN, Master

#703 Update the old webui screenshot to exclude the vcenter plugin.
  userguide/images/tn_webinterface.png
Labels: FN/TN, Master

#704 Update truenas login screenshot.
  userguide/images/tn_login1c.png
Labels: FN/TN, Master

#705 Updated 2 screenshots in truenas/master
  userguide/images/services-asigra.png
  userguide/images/tn_guide.png
Labels: FN/TN, Master

#706 72755 (11.2-U3): Define a Docker Host replacement
  userguide/conf.py
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#707 Revert "72755 (11.2-U3): Define a Docker Host replacement"
  userguide/conf.py
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#708 72755 (11.2-U3): Define Docker Host replacement
  userguide/conf.py
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN, Ready to Merge

#710 72755 (11.2-U3) Define Docker VM replacement
  userguide/conf.py
  userguide/vms.rst
Labels: FN/TN, Master, Ready to Merge

#711 70545 (11.2-U3): Replace re0 ifconfig example in intro.rst
  userguide/intro.rst
Labels: Angulargui, FN/TN, Ready to Merge

#712 70545 (11.2-U3): Replace re0 ifconfig example in intro.rst
  userguide/intro.rst
Labels: FN/TN, Master, Ready to Merge

#713 67870 (11.2-U3): Rework Domain Controller and Global Catalog Server field descr…
  userguide/directoryservices.rst
Labels: Angulargui, FN/TN, Ready to Merge

#714 67870 (11.2-U3): Rework Domain Controller and Global Catalog Server f…
  userguide/directoryservice.rst
Labels: FN/TN, Master, Ready to Merge

#716 66430 (11.2-U3): Clarify replication process and interruptions.
  userguide/tasks.rst
Labels: Angulargui, FN/TN, Ready to Merge

#717 66430 (11.2-U3): Clarify replication process and interruptions.
  userguide/storage.rst
Labels: FN/TN, Master, Ready to Merge

#719 58392 (11.2-U3): Add ZFS Feature Flags section and new references to this section
  userguide/install.rst
  userguide/snippets/alertevents.rst
  userguide/snippets/upgradingazfspool.rst
  userguide/storage.rst
  userguide/zfsprimer.rst
Labels: Angulargui, FN/TN

#729 58392 (11.2-U3): Add ZFS Feature Flags section and new references to this section
  userguide/install.rst
  userguide/snippets/alertevents.rst
  userguide/snippets/upgradingazfspool.rst
  userguide/storage.rst
  userguide/zfsprimer.rst
Labels: FN/TN, Master

#727 69625: Rework Init/Shutdown Tasks section.
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#728 69625: Rework Init/Shutdown Tasks section.
  userguide/tasks.rst
Labels: FN/TN, Master

#721 75397: Update the list of default tunables and sysctl's.
  userguide/system.rst
Labels: FN/TN, Master

#722 75397: Update the list of default tunables and sysctl's.
  userguide/system.rst
Labels: Angulargui, FN/TN
