Repository freenas/freenas-docs, pull requests merged in 2019-10, with the labels that each got.

#1557 NAS-103195: Rewrite 'noacl' entry in "Available VFS Objects" table.
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1564 NAS-103227: Advanced Replication: Indicate "Direction" no longer appe…
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1569 NAS-103265: Remove iocage cli instructions.
  userguide/Makefile
  userguide/conf.py
  userguide/images/jail-shell-example.png
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1573 NAS-101045: Remove TrueNAS System/Information section
  userguide/images/truenas/dashboard.png
  userguide/images/truenas/system-information.png
  userguide/system.rst
  userguide/tn_initial.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1572 Update to updated EULA (cherry-pick from master).
  userguide/tn_eula.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1575 Remove orphaned images/truenas screenshots.
  userguide/images/truenas/iscsi_target_global.png
  userguide/images/truenas/network-global.png
  userguide/images/truenas/services-asigra.png
  userguide/images/truenas/storage-dataset.png
  userguide/images/truenas/system-boot.png
  userguide/images/truenas/system-ca.png
  userguide/images/truenas/system-cert.png
  userguide/images/truenas/vcenter-datastore-clone.png
  userguide/images/truenas/vcenter-datastore-config-nfs.png
  userguide/images/truenas/vcenter-datastore-confirm-nfs.png
  userguide/images/truenas/vcenter-datastore-confirm-vmfs.png
  userguide/images/truenas/vcenter-datastore-create-hostselection.png
  userguide/images/truenas/vcenter-datastore-extend.png
  userguide/images/truenas/vcenter-datastore-vmfs-config.png
  userguide/images/truenas/vcenter-extent-create.png
  userguide/images/truenas/vcenter-new-periodic-snapshot.png
  userguide/images/truenas/vcenter-newhost.png
  userguide/images/truenas/vcenter-plugin-config.png
  userguide/images/truenas/vcenter-plugin-secure.png
  userguide/images/truenas/vcenter-replication-create.png
  userguide/images/truenas/vcenter-snapshot-manage.png
  userguide/images/truenas/vcenter-target-create.png
  userguide/images/truenas/vcenter-target-edit.png
  userguide/images/truenas/vcenter-zvol-create.png
  userguide/images/truenas/vcenter-zvol-edit.png
  userguide/images/truenas/view.png
  userguide/images/truenas/volume2.png
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1570 NAS-103131: Begin updating 'Dynamic DNS' docs section
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1574 NAS-101052 doc installing docker to VM on FN.
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1584 NAS-103355 Remove NetData docs
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1585 NAS-101139: Update OAuth text for cloud credentials
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1555 NAS-101272: synchronize 'Replication Task Options' table with UI help…
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1581 NAS-102800 doc zvol size field in "add zvol"
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1583 NAS-100563 reviewed preferences section and updated with new changes
  userguide/settings.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1578 NAS-103321 doc system>general> language field changes
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1550 NAS-103099: Rewrite TrueNAS HA update instructions
  userguide/images/truenas/system-update-ha-failover.png
  userguide/images/truenas/system-update-ha-pending.png
  userguide/images/truenas/system-update.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1587 NAS-103399 Update docs for new repeat vdev functionality
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1576 NAS-103195: sync noacl description with 11.2-legacy branch
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#1586 NAS-103484 Update VM docs about available memory
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1592 TrueNAS 11.2-U6.1: Update guide images for new release.
  userguide/images/tn_system-information.png
  userguide/images/tn_webinterface.png
Labels: 11.2-legacy, TrueNAS

#1588 NAS-103458: Sync iSCSI wizard 'Authorized Networks' description with …
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1594 NAS-103369: Add text about B2 sync default behavior.
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1595 NAS-102955 Update description of Rsync path checking.
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN
