Repository freenas/freenas-docs, pull requests merged in 2019-08, with the labels that each got.

#1313 NAS-101569 doc sending email for manual cron task
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1354 Update pdf headers to include the legacy deprecate msg
  userguide/conf.py
  userguide/tn_intro.rst
Labels: 11.3 Beta 1, TrueNAS

#1237 NAS-101538 add docs for not using space in task schedulers.
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1310 NAS-100329 doc VMs individual log files.
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1324 NAS-100822 doc new "Reporting" page.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1370 NAS-102683: Update change log for 11.3
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1299 Fix periodic snapshot task and replication task documentation inaccur…
  userguide/storage.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1350 Port replication text updates from PR #1299 to angulargui branch
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1353 NAS-102561: Finish draft rewrite of Pool Encryption docs
  userguide/storage.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1355 NAS-100319 change ip4_saddrsel name also
  userguide/intro.rst
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1363 NAS-100345: Add intro note about new file.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1365 NAS-102460: Remove BIOS and IPMI config instructions from guide
  userguide/images/truenas/BIOS1.png
  userguide/images/truenas/BIOS2.png
  userguide/images/truenas/BIOS3.png
  userguide/images/truenas/BIOS4.png
  userguide/images/truenas/BIOS5.png
  userguide/images/truenas/BIOS6.png
  userguide/images/truenas/IPMIaccept.png
  userguide/images/truenas/IPMIcontinue.png
  userguide/images/truenas/IPMIdownload.png
  userguide/images/truenas/IPMIjava.png
  userguide/images/truenas/IPMIlogin.png
  userguide/network.rst
  userguide/tn_initial.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1364 NAS-100007: Add entry for AD related alerts
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1367 NAS-101537: Review DirectoryServices docs
  userguide/directoryservices.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1369 NAS-102728 doc reporting graphs not displaying without data
  userguide/intro.rst
  userguide/reporting.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1372 Update network-global.png for angulargui TrueNAS guide:
  userguide/images/truenas/network-global.png
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1340 Intro entry for viewing replication tasks logs
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1356 NAS-102367 docs warning when editing top-level dataset ACL
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1357 NAS-102251 doc removal of asigra from service page
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1360 NAS-101610 doc refresh index button for plugins
  userguide/intro.rst
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1361 NAS-100818 doc post install button for plugins
  userguide/intro.rst
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1379 NAS-102460: Remove BIOS and IPMI config instructions from 11.2-legacy guides
  userguide/network.rst
  userguide/tn_initial.rst
Labels: 11.2-legacy, FN/TN

#1380 NAS-102266: Port VIP/VHID description changes to 11.2-legacy
  userguide/system.rst
Labels: 11.2-legacy, FN/TN

#1386 NAS-102460: Move tn_hardware content to tn_initial.
  userguide/tn_hardware.rst
  userguide/tn_initial.rst
  userguide/truenas.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1387 NAS-102460: Move tn_hardware content to tn_initial.
  userguide/images/tn_BIOS1.png
  userguide/images/tn_BIOS2.png
  userguide/images/tn_BIOS3.png
  userguide/images/tn_BIOS4.png
  userguide/images/tn_BIOS5.png
  userguide/images/tn_BIOS6.png
  userguide/images/tn_IPMI_console_show.png
  userguide/images/tn_IPMIlogin.png
  userguide/tn_hardware.rst
  userguide/tn_initial.rst
  userguide/truenas.rst
Labels: 11.2-legacy, TrueNAS

#1368 NAS-102266: Update Virtual IP and VHID descriptions
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, Ready to Merge, TrueNAS

#1382 NAS-100091: Update LDAP hostname field description.
  userguide/directoryservices.rst
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1396 NAS-102258 sync allow guest access descrip with helptext
  userguide/sharing.rst
Labels: 11.2-angular, 11.3 Beta 1, FN/TN

#1399 NAS-101516 Clarify intro for remove periodic notification user
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1385 NAS-101537: Add intro entries for removed fields.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1362 NAS-102733 minor update to docs about exporting pool
  userguide/images/storage-pools-actions-detach.png
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1378 NAS-101049 intro entry for grub boot loader (again)
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1383 NAS-100182 clarify docs on replacing disk to expand pool
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1366 NAS-100913 doc DOCUMENTATION option for plugins
  userguide/intro.rst
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1373 NAS-100177 doc directory service monitor
  userguide/directoryservices.rst
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1375 NAS-101567 doc location of ssh keys
  userguide/system.rst
Labels: 11.2-angular, 11.3 Beta 1, FN/TN

#1374 NAS-101567 doc location of ssh keys.
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1392 NAS-102656: Update 'Permission Options' table to synchronize with rev…
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1394 NAS-101569 remove redundancy of manual cron task email
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1397 NAS-102258 sync allow guest access descrip with helptext
  userguide/sharing.rst
Labels: 11.2-legacy, 11.3 Beta 1, FN/TN

#1400 NAS-100069: Add Initiate Failover button to Failover docs.
  userguide/images/truenas/system-failover.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1402 update replication task log tense
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1403 NAS-100321: Update NetBIOS Name field descriptions in the Active Dire…
  userguide/directoryservices.rst
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1406 NAS-100225: Add text to Import Disk section about viewing log.
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1407 NAS-100431: Add intro entry about periodic alert backend switch.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1408 NAS-102066 update descrip of Initiators
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1398 NAS-102332 verfiy units for Limit in rep tasks
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1377 NAS-100822 doc new reporting options, NFS and UPS
  userguide/intro.rst
  userguide/reporting.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1384 NAS-101836 doc temperature monitoring HDD standby
  userguide/reporting.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1393 NAS-100348 add intro entry for removal of Default Permissions
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1391 NAS-100543 clean up docs for deleting dataset
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1419 Fix TrueNAS guide build error
  userguide/system.rst
Labels: TrueNAS

#1388 NAS-102087: Rework Sharing chapter intro section.
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1405 NAS-100822 doc dynamic function of changing system>reporting options
  userguide/reporting.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1389 NAS-102683: Refine changelog
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1412 NAS-102868: Remove pool space recommendation from ZFS Primer.
  userguide/zfsprimer.rst
Labels: 11.2-angular, FN/TN

#1413 NAS-102868: Remove pool space recommendation from ZFS Primer.
  userguide/zfsprimer.rst
Labels: 11.2-legacy, FN/TN

#1414 NAS-102868: Remove pool space recommendation from ZFS Primer.
  userguide/zfsprimer.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1415 NAS-102868: Remove pool space recommendation from ZFS Primer.
  userguide/zfsprimer.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1416 NAS-102798 remove netbios name and alias from ldap page
  userguide/directoryservices.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1417 NAS-102735 doc software version on man update page
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1422 NAS-102798 intro for removal of netbios name and alias.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1358 NAS-102252 doc removal of asigra from service page
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1401 Update asigra plugin descrip with feedback.
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1359 NAS-102136 doc additional disk info being added to disk page
  userguide/directoryservices.rst
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1411 NAS-100710: Add new fields to Disk Options table.
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1425 NAS-100747: Review/update TrueNAS Network/Global Configuration text.
  userguide/network.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1342 docs "NAT" checkbox for jails
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1418 NAS-100372: Add text about automatic swap partitions
  userguide/install.rst
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1376 NAS-102104 doc SMB recycle bin caveat.
  userguide/sharing.rst
Labels: Angulargui, FN 11.2-U6, FN/TN

#1426 NAS-100821: Add EC crypto support
  userguide/images/system-cas-add-internal-ca.png
  userguide/images/system-certificates-add-internal-certificate.png
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1427 NAS-102657 doc "From Name" field in System>Email
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1409 NAS-100481: Synchronize iSCSI field descriptions with UI help text
  userguide/conf.py
  userguide/images/sharing-block-iscsi-initiators-add.png
  userguide/images/sharing-block-iscsi-initiators-example.png
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1410 NAS-100516: Add Netdata configuration options to Services chapter.
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1423 NAS-100746: Review/update TrueNAS Support page
  userguide/images/truenas/system-support.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1371 NAS-101914 doc jails/plugins being license for TN
  userguide/jails.rst
  userguide/plugins.rst
  userguide/snippets/license.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1395 NAS-102258 sync allow guest access descrip with helptext
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1404 NAS-100502: Finish initial draft of ACME documentation
  userguide/images/system-acme-cert-add.png
  userguide/images/system-acmedns-add.png
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1420 NAS-102547 doc VNC setting in VM wizard
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1428 NAS-100369: VM Description
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1421 NAS-100585: finish cleaning TrueNAS Failover section
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1433 Cherry-pick docs for location of ssh keys
  userguide/system.rst
Labels: 11.2-legacy, 11.3 Beta 1, FN/TN

#1434 NAS-102718: Review Encrypted Pool/Disk operations
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1435 Cherry-pick docs for SMB recycle bin caveat
  userguide/sharing.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1436 NAS-102104 port docs to 11.2-legacy for SMB recycle bin caveat
  userguide/sharing.rst
Labels: 11.2-legacy, FN 11.2-U6, FN/TN

#1438 NAS-100911: Add intro entry for Chunk Size field in Cloud Sync Tasks …
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1456 Fix typo
  userguide/sharing.rst
Labels: 11.2-legacy, FN 11.2-U6, FN/TN

#1461 NAS-102912: Update 'Client Time Machine Configuration' subsection
  userguide/sharing.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1462 NAS-102912: Update 'Client Time Machine Configuration' subsection
  userguide/sharing.rst
Labels: Angulargui, FN 11.2-U6, FN/TN

#1464 NAS-102152: Add caution about powering on VMs
  userguide/storage.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1424 Update and clarify manual update section.
  userguide/images/save-config.png
  userguide/images/system-manualupdate.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1466 NAS-102912: Update 'Client Time Machine Configuration' subsection
  userguide/sharing.rst
Labels: 11.2-legacy, Angulargui, FN 11.2-U6

#1467 NAS-102152: update text a little from offline feedback.
  userguide/storage.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1468 NAS-102152: Add caution about powering on VMs
  userguide/storage.rst
Labels: 11.2-legacy, FN 11.2-U6, FN/TN

#1441 NAS-100894: Import Certificate Signing Request
  userguide/images/system-certificates-add-import-certificate.png
  userguide/images/system-certificates-add-internal-certificate.png
  userguide/images/system-certificates.png
  userguide/images/truenas/system-cert.png
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1443 NAS-101293: Update Available VFS Modules table
  userguide/intro.rst
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1465 NAS-102152: Add caution about powering on VMs
  userguide/storage.rst
Labels: Angulargui, FN 11.2-U6, FN/TN

#1446 NAS-101416: Update Network/Interfaces Parent Interface description
  userguide/network.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1447 NAS-101473: Update TrueNAS IPMI description
  userguide/images/truenas/network-ipmi.png
  userguide/network.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1449 NAS-101749: Update ACL Manager section
  userguide/images/storage-acls.png
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1450 NAS-101943: Update export pool text
  userguide/images/storage-pools-actions-detach.png
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1455 NAS-102300: Update FreeNAS System/Support section
  userguide/images/system-support.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1470 Sync 11.2-angular manual update text with angulargui
  userguide/images/save-config.png
  userguide/images/system-manualupdate.png
  userguide/system.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1471 sync endpoint URL doc descrip with updated helptext
  userguide/system.rst
Labels: Angulargui, FN 11.2-U6, FN/TN

#1472 sync endpoint URL doc descrip with updated helptext
  userguide/system.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1474 NAS-102240: Update 'Cloud Credential Options' table
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1432 NAS-102865 rewrite "Replacing drives to grow a ZFS pool" section
  userguide/storage.rst
Labels: 11.2-legacy, 11.3 Beta 1, FN/TN

#1488 Sync help text and guide descrip: Limit (KiB/s) field
  userguide/tasks.rst
Labels: Angulargui, FN 11.2-U6, FN/TN

#1483 NAS-102558: Update encryption operations
  userguide/images/storage-pools-encrypt-passphrase.png
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1484 NAS-102777: Update 'replace failed disk' section
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1480 NAS-102300: Add text about private attachments
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1485 NAS-102632: Add text about ACL editing to SMB Sharing section
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1489 NAS-102193: Update note about edit/delete TrueNAS HA interfaces
  userguide/network.rst
Labels: 11.3 Beta 1, Master, TrueNAS

#1487 NAS-102193: Update note about edit/delete TrueNAS HA interfaces
  userguide/network.rst
Labels: 11.2-legacy, FN 11.2-U6, TrueNAS

#1457 NAS-102301: Add general usage note about expanding list entries
  userguide/booting.rst
  userguide/intro.rst
  userguide/snippets/usingui.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1491 NAS-102300: Remove reference to obsolete "document vault"
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1475 NAS-100942: Update WebDAV 'Change User and Group Ownership' field des…
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN
