Repository freenas/freenas-docs, pull requests merged in 2019-11, with the labels that each got.

#1597 DOCS-62: Recrop dialog screenshots
  userguide/images/alert-example.png
  userguide/images/custom-scheduler.png
  userguide/images/power-restart.png
  userguide/images/power-shut-down.png
  userguide/images/save-config.png
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1598 NAS-102047: Review references to "Share Type" and sync with recent ch…
  userguide/services.rst
Labels: 11.3 Beta 2

#1600 NAS-103528: Remove graphite server and report cpu in percentage field…
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 2, Angulargui

#1589 NAS-101045: Rework TrueNAS specific Dashboard section into new snippet.
  userguide/booting.rst
  userguide/images/truenas/log-in.png
  userguide/intro.rst
  userguide/snippets/ui_login.rst
  userguide/tn_initial.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1601 NAS-103194: Update plugin delete procedure.
  userguide/images/plugins-delete-example.png
  userguide/plugins.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1603 NAS-102963: Sync updated B2 cloud cred field names and helptext with …
  userguide/system.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1604 NAS-103963: Sync up 11.2 Backblaze B2 cloud sync cred fields with docs.
  userguide/system.rst
Labels: 11.2-U7, 11.2-angular, FN/TN

#1602 NAS-103292: Update cloud sync status description:
  userguide/images/tasks-cloud-sync-tasks.png
  userguide/tasks.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1609 NAS-103565 Change "jiffies" to "units of kenerl time"
  userguide/system.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1606 Add intro for new SNMP trap alert service.
  userguide/intro.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1607 NAS-103922 Update S3 secret and access key standards.
  userguide/system.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1612 NAS-103528: Clean up remaining mentions of Graphite.
  userguide/reporting.rst
  userguide/system.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1608 DOCS-68 Add note about removing installation media for VM.
  userguide/virtualmachines.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1613 NAS-101139: Resync 11.2-legacy Cloud Provider text with angular
  userguide/system.rst
Labels: 11.2-U7, 11.2-legacy, FN/TN

#1614 NAS-101139: Update OAuth docs for 11.2-U7
  userguide/intro.rst
  userguide/system.rst
Labels: 11.2-U7, 11.2-angular, FN/TN

#1615 DOCS-73 remove extranous mention of dataset in sharing chapter
  userguide/sharing.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1617 NAS-103770: Update `Allow Local User Login` description
  userguide/services.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1599 NAS-101310: Update replication "State" to describe realtime updates
  userguide/tasks.rst
Labels: 11.3 Beta 2, Angulargui

#1620 NAS-100153 Update create plugin docs with regard to new community repo
  userguide/plugins.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1619 NAS-101549 Update guide to match Syslog Server helptext.
  userguide/system.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1618 NAS-103774: Update Settings/Change Password text
  userguide/settings.rst
Labels: 11.3 Beta 2, Angulargui, FN/TN

#1623 NAS-103773: Review and update encryption options for Cloud Sync Tasks.
  userguide/tasks.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1624 NAS-103892: Add tip for MacOS clients and SMB share guest access.
  userguide/sharing.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1626 NAS-103773: Retest and cherry-pick Cloud Sync Task Encryption text im…
  userguide/tasks.rst
Labels: 11.2-legacy, FN/TN

#1625 NAS-103773: Retest and cherry-pick Cloud Sync Task Encryption text im…
  userguide/tasks.rst
Labels: 11.2-angular, FN/TN

#1627 NAS-103773: resync text across branches
  userguide/tasks.rst
Labels: 11.3 RC1, Angulargui, FN/TN
