Repository freenas/freenas-docs, pull requests merged in 2019-07, with the labels that each got.

#1222 NAS-101277: Add 'Exclude' periodic snapshot task field docs
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1206 NAS-102112: Add entries for "Disable LDAP user/group cache" checkbox.
  userguide/directoryservices.rst
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1207 NAS-102040: Add descriptions of chain delete/disable for SSH Connecti…
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1209 NAS-101693 add docs for search functionality on UPS>Driver field
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1194 NAS-101051 comment out all of docker docs
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1254 NAS-102313 reindex entires in vm options table.
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1213 NAS-100052 Docs for VM autostart in an encrypted, locked pool
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1174 NAS-100021: Add one-time replication example
  userguide/storage.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1202 NAS-102188: Rework dataset delete instructions and add intro entry
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1203 NAS-102188: Update dataset delete description and add warning
  userguide/storage.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1212 NAS-100052 Docs for VM autostart in an encrypted, locked pool
  userguide/vms.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1216 NAS-100129: Document 'Use --fast-list' checkbox.
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1217 NAS-100313: Update services-smb.png and tn_cifs1b.png images
  userguide/images/services-smb.png
  userguide/images/tn_cifs1b.png
Labels: 11.3 Beta 1, FN/TN, Master

#1208 NAS-102125 add docs for disk type, rotation rate, and model
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1204 NAS-102138 add docs for "Storage Class" field in Cloud Sync Task
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1211 NAS-100084 update docs for updated snapshot page
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1235 NAS-101675 docs for email alert when proactive support ticket fails
  userguide/snippets/alertevents.rst
  userguide/system.rst
Labels: 11.2-U5, Master, TrueNAS

#1236 NAS-101675 docs for email alert when proactive support ticket fails
  userguide/snippets/alertevents.rst
  userguide/system.rst
Labels: 11.2-U5, 11.2-legacy, TrueNAS

#1238 NAS-101771: Update tn_webinterface.png and tn_vcenter.rst for TrueNAS 11.2-U5
  userguide/images/tn_webinterface.png
  userguide/tn_vcenter.rst
Labels: 11.2-U5, 11.2-legacy, TrueNAS

#1244 NAS-102231: Review creating OneDrive cloud credential and update docs
  userguide/system.rst
Labels: 11.2-U5, 11.2-legacy, FN/TN

#1250 NAS-102234: Remove Amazon Cloud Drive from System/Cloud Credentials
  userguide/images/system-cloud-credentials-add.png
  userguide/system.rst
Labels: 11.2-U5, 11.2-legacy, FN/TN

#1266 NAS-101675: docs for email alert when proactive support ticket fails
  userguide/snippets/alertevents.rst
  userguide/system.rst
Labels: 11.2-U5, Angulargui, FN/TN

#1247 NAS-102231: Update System/Cloud Credentials to include OAuth text
  userguide/images/system-cloud-credentials-add-example.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1248 NAS-102231: Cherry-pick 11.2-legacy OAuth changes and review text for 11.3
  userguide/images/system-cloud-credentials-add.png
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1249 NAS-102234: Remove Amazon Cloud Drive provider.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1246 NAS-102231: (FN 11.2-U6) Manually port OAuth text additions to System/Cloud Creden…
  userguide/system.rst
Labels: 11.2-angular, FN/TN

#1224 NAS-101505: Document 'Expose zilstat via SNMP` field.
  userguide/images/services-snmp.png
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1225 NAS-101996: Expand description of 'Private Key' field in SSH Connecti…
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1226 NAS-101109: Review ported SSH Keypairs text and update for master bra…
  userguide/images/system-ssh-keypairs-add.png
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1227 NAS-101108: Review ported SSH Connections text and update for legacy ui
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1228 NAS-102241: Update replication descriptions to expand 'Source Dataset…
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1229 NAS-101110: Review UI fields that are part of Replication tasks
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1231 NAS-102249 docs for iSCSI wizard
  userguide/intro.rst
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1233 NAS-101100 docs for snapshot failed alert
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1234 NAS-101100 docs for snapshot failed alert
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1239 Plugin council task11.2angular
  userguide/jails.rst
Labels: 11.2-angular, FN/TN

#1240 NAS-100703 docs for cloud sync fail alert
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1241 Nas-100703 add cloud sync error to error list.
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1242 Redirect docs to new ui for plugins and jails
  userguide/jails.rst
  userguide/plugins.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1243 NAS-102277 remove docs for theme selector tool.
  userguide/settings.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1245 NAS-102339 Remove docs for "Add to Favorites" settings.
  userguide/settings.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1251 NAS-101927: Update "Exclude" description in Periodic Snapshot Tasks
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1252 NAS-101927: Update "Exclude" description in Storage/Periodic Snapshot…
  userguide/storage.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1255 NAS-102259 sync SMB doc options with whats available in UI
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1256 NAS-102200 docs for field name change in VM wiz
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1257 NAS-100740: Add note about converting SSH configs to SSH Keypair entries.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1258 NAS-100740: Add note about converting SSH configs to SSH Keypair entr…
  userguide/intro.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1259 NAS-100824: Update System/General documentation
  userguide/images/system-general.png
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1260 NAS-100824: Sync System/General docs with angulargui branch where pos…
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1261 NAS-100959: new alert when cloud sync task fails.
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1262 NAS-100959: new alert when cloud sync task fails.
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1264 NAS-101026: Communicate that Cloud Sync tasks run sequentially
  userguide/tasks.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1265 NAS-101026: Communicate that Cloud Sync tasks run sequentially
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1267 Update tn_webinterface and tn_vcenter for 11.3
  userguide/images/tn_webinterface.png
  userguide/tn_vcenter.rst
Labels: 11.3 Beta 1, Master, TrueNAS

#1268 Port tn_vcenter improvements to angulargui branch
  userguide/tn_vcenter.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1269 Clarify Amazon Drive link (FreeNAS 11.2-U6 only)
  userguide/intro.rst
Labels: 11.2-legacy, FN 11.2-U6

#1270 NAS-102231: Fix up hubiC text
  userguide/system.rst
Labels: 11.2-U5, FN/TN, Master

#1271 NAS-102231: Sync hubiC changes with #1270
  userguide/system.rst
Labels: 11.2-U5, Angulargui, FN/TN

#1272 NAS-100050 docs for snapshot lifetime unit field.
  userguide/storage.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1274 Angulargui branch: Fix all TrueNAS guide build warnings
  userguide/images/display-system-processes.png
  userguide/images/truenas/display-system-processes.png
  userguide/images/truenas/reboot.png
  userguide/images/truenas/shell.png
  userguide/images/truenas/shutdown.png
  userguide/services.rst
  userguide/system.rst
  userguide/tn_options.rst
  userguide/truenas.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1219 NAS-101933: Add "Allow taking empty snapshots" docs
  userguide/images/tasks-periodic-snapshot-tasks-add.png
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1253 NAS-100911: Add b2-chunk-size field docs
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1214 NAS-100895: Reorganize network.rst and add initial text review
  userguide/images/network-link-aggregations-add.png
  userguide/images/network-link-aggregations-edit.png
  userguide/images/network-vlans-add.png
  userguide/intro.rst
  userguide/network.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1215 NAS-100038: Add new System > Reporting screen to legacy UI docs
  userguide/images/system-reporting.png
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1218 NAS-100609: Update Storage/Import Disk text to describe filesystem au…
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1230 NAS-100040: Update local replication example section.
  userguide/storage.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1273 NAS-100141 docs for "fetch method" for plugin/jail releases.
  userguide/jails.rst
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1275 NAS-101737 fix typo
  userguide/sharing.rst
Labels: Angulargui, FN 11.2-U6, FN/TN

#1276 Nas-101737 fix typo
  userguide/sharing.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1277 NAS-101737 fix typo
  userguide/sharing.rst
Labels: FN 11.2-U6, FN/TN, freenas/11.1-stable

#1278 NAS-102329: Update docs for default view in Accounts/Users
  userguide/accounts.rst
  userguide/images/accounts-users.png
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1281 NAS-101273 docs for snapshot lifetime units field.
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1282 NAS-102239: Update fields in "Global SMB Options" table
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1290 Manually build, review, and update images related to the TrueNAS 11.2…
  userguide/images/authorized1.png
  userguide/images/auto1.png
  userguide/images/cloudsync-example-cred.png
  userguide/images/network-ipmi.png
  userguide/images/sharing-iscsi-extent-add.png
  userguide/images/tn_system-information.png
Labels: 11.2-U5, 11.2-legacy, FN/TN

#1283 NAS-102328 docs for updated VM page
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN, don't merge yet

#1284 NAS-102259 intro entry for changes to SMB service options
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1285 NAS-100707 add intro entry for jail/plugin migration to iocage.
  userguide/intro.rst
  userguide/jails.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1286 NAS-102339 intro entry for removing add to fav. checkbox
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1289 NAS-101273 Intro for 2 new snapshot tasks fields
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1291 The rest of PR #1283
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1287 NAS-102277 intro for theme selector removal and hostname move.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1288 NAS-100141 intro entry for fetch method.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1279 NAS-102256: Update "Bind IP Addresses" in "Global SMB Configuration O…
  userguide/services.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1280 NAS-102256: Update "Bind IP Addresses" in "Global SMB Configuration O…
  userguide/services.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1293 NAS-100824: Update truenas/system-general image
  userguide/images/truenas/system-general.png
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1294 NAS-100824: Update system general images (FN and TN)
  userguide/images/system-general.png
  userguide/images/tn_system-general.png
Labels: 11.3 Beta 1, FN/TN, Master

#1292 NAS-102047: Add ACL mode/manager docs
  userguide/images/storage-acls.png
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1302 NAS-100833 intro entry for new field in jail properties.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1301 NAS-102201: Update scrub pause alert condition
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1300 NAS-102201: Update scrub pause alert condition
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1303 NAS-102047: Update ACL Manager section from Andrew's notes
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1295 NAS-102213 update alert docs
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1307 NAS-100121: Update System/Cloud Cred/SFTP field
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1308 NAS-100121: Update System/Cloud Cred/SFTP field
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1223 NAS-100173 docs for host.domain name being always visible.
  userguide/intro.rst
  userguide/network.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1314 Remove docs for SMB field that didn't exist in UI
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1320 Update Tasks/Cloud Sync table and example images.
  userguide/images/tasks-cloud-sync-tasks-add.png
  userguide/images/tasks-cloud-sync-tasks-example.png
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1322 NAS-101744: Update Alert Services for new OpsGenie field.
  userguide/images/system-alert-services-add.png
  userguide/images/system-alert-services.png
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1321 NAS-100432 doc console access while web UI loads.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1315 NAS-100543 doc force delete dataset when busy dialog.
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1298 NAS-101423 doc the msg about available memory for VM
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1304 NAS-101349 UPS events now use Alerts
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1305 NAS-101349 UPS events now use Alerts
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1309 NAS-100329 Doc VMs individual log files
  userguide/intro.rst
  userguide/vms.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1311 NAS-102098 doc new column in Tasks->Replication Tasks
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1232 NAS-101507 docs for updating plugin release
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1306 NAS-100471 docs Renamed "Boot environments" to "Boot"
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1316 NAS-102332 update table entry for Limit field in Tasks->Rep Tasks-> Add
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1296 NAS-101963 doc that replication task names are unique
  userguide/intro.rst
  userguide/system.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1317 NAS-102299: Update OAuth Cloud Credentials descriptions
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1319 NAS-101923 doc "Replication Performance" field appearance condition
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1323 NAS-100280: Update Alert Services docs
  userguide/images/system-alert-services-add.png
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1325 NAS-101292 intro entry for DOS Charset removal.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1327 NAS-101732: Review and update ACL manager text:
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1328 NAS-100203 doc shell right click snackbar message
  userguide/intro.rst
  userguide/shell.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1329 NAS-102082: Plugin delete update
  userguide/images/plugins-delete-example.png
  userguide/intro.rst
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1343 NAS-101582: Update jail wizard networking instructions.
  userguide/conf.py
  userguide/images/jails-add-wizard-networking.png
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1330 NAS-102087: Add clarification about SMB share delete
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1331 NAS-102033: Update Shell image and text
  userguide/images/shell.png
  userguide/shell.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1339 NAS-100168: Satadom wear alert
  userguide/snippets/alertevents.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1345 NAS-102396 Clarify wording for hot spares
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1346 NAS-102396 Clarify wording for hot spares
  userguide/storage.rst
Labels: 11.2-angular, FN 11.2-U6, FN/TN

#1334 NAS-102023: Update ixnas VFS module description
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1333 NAS-102218: Small update to System/Email text
  userguide/images/system-email.png
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1335 NAS-100374 remove doc for "reporting database" field.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1347 NAS-102396 Clarify wording for hot spares
  userguide/storage.rst
Labels: 11.2-legacy, FN 11.2-U6, FN/TN

#1348 NAS-102631 disable HA before exporting last pool.
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1337 NAS-100319 docs for ip6_saddrsel name change
  userguide/intro.rst
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1312 NAS-101569 doc sending email for manual cron task
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1344 port the changes from #1310
  userguide/intro.rst
  userguide/vms.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1349 Fix speed limit descrip. in rep. task table
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1351 NAS-102527 add big warning box for deprecated legacyUI
  userguide/_static/themes/trueos_style/static/css/legacy_deprecate.css
  userguide/_static/themes/trueos_style/static/css/trueos_style.css
  userguide/account.rst
  userguide/alert.rst
  userguide/api.rst
  userguide/cinder.rst
  userguide/cli.rst
  userguide/contribute.rst
  userguide/directoryservice.rst
  userguide/help.rst
  userguide/install.rst
  userguide/intro.rst
  userguide/jails.rst
  userguide/logout.rst
  userguide/network.rst
  userguide/plugins.rst
  userguide/processes.rst
  userguide/quick.rst
  userguide/reboot.rst
  userguide/reporting.rst
  userguide/services.rst
  userguide/sharing.rst
  userguide/shell.rst
  userguide/shutdown.rst
  userguide/snippets/legacy_deprecate.rst
  userguide/storage.rst
  userguide/support.rst
  userguide/system.rst
  userguide/tasks.rst
  userguide/tn_eula.rst
  userguide/tn_hardware.rst
  userguide/tn_initial.rst
  userguide/tn_intro.rst
  userguide/tn_options.rst
  userguide/tn_vcenter.rst
  userguide/vaai.rst
  userguide/vms.rst
  userguide/wizard.rst
  userguide/zfsprimer.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1326 intro entry for removal of docker
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1341 intro entry for Storage class field in cloud sync tasks
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN
