Repository freenas/freenas-docs, pull requests merged in 2019-05, with the labels that each got.

#1030 Catch the last of the "boot device" stragglers.
  userguide/system.rst
Labels: 11.2-angular, FN/TN

#1029 Catch the last of the "boot device" stragglers.
  userguide/system.rst
Labels: Angulargui, FN/TN

#1031 NAS-101555: vmware text improvements master
  userguide/install.rst
Labels: FN/TN, Master

#1032 NAS-100154: Confirm TrueNAS guide builds and changes for this ticket …
  userguide/sharing.rst
Labels: Angulargui, TrueNAS

#1034 NAS-100905: Fix typo
  userguide/tn_initial.rst
Labels: Master, TrueNAS

#1035 NAS-100905: Fix typo
  userguide/tn_initial.rst
Labels: Angulargui, TrueNAS

#1036 NAS-100905: Fix typo
  userguide/tn_initial.rst
Labels: 11.2-legacy, TrueNAS

#1052 Port changes from master to angulargui.
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1053 86580: ES24 BSG Re-edit back panel image and rework descriptive text.
  userguide/images/tn_es24_back.png
  userguide/snippets/es24.rst
Labels: BSG, Master

#1055 ES24 BSG: Update indicators image and text a little.
  userguide/images/tn_es24_indicators.png
  userguide/snippets/es24.rst
Labels: BSG, Master

#1056 Enlarge screws on couple es24 photos
  userguide/images/tn_es24m_cabinet_rail2.png
  userguide/images/tn_es24m_mount_system.png
Labels: BSG, Master

#1023 NAS-100153 11.2angular
  userguide/plugins.rst
Labels: 11.2-angular, FN/TN

#1058 NAS-100153 Revert the plugin creation instructions.
  userguide/plugins.rst
Labels: 11.2-angular, FN/TN

#1057 NAS-100153 Revert the plugin creation instructions.
  userguide/plugins.rst
Labels: Angulargui, FN/TN

#1050 Synchronize current System/Cloud Credentials/S3/Endpoint URL help tex…
  userguide/system.rst
Labels: Angulargui, FN/TN

#998 NAS-100799 Updated the description of creating user home directory.
  userguide/account.rst
Labels: FN/TN, Master

#999 NAS-100799 Updated the description of creating user home directory.
  userguide/account.rst
Labels: 11.2-legacy, FN/TN

#1000 NAS-100799 Updated the description of creating user home directory.
  userguide/accounts.rst
Labels: 11.2-U5, Angulargui, FN/TN

#1001 NAS-100799 Updated the description of creating user home directory.
  userguide/accounts.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1004 11.2-U4 Legacy UI: Update screenshots
  userguide/images/install2c.png
  userguide/images/services-snmp.png
Labels: 11.2-legacy, FN/TN

#1012 NAS-101586: Add configurables to ixnas entry in "Available VFS Module…
  userguide/sharing.rst
Labels: FN/TN, Master

#1013 NAS-101586: Add configurables to ixnas entry in "Available VFS Module…
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#1014 NAS-101586: Add configurables to ixnas entry in "Available VFS Module…
  userguide/sharing.rst
Labels: 11.2-U5, 11.2-legacy, FN/TN

#1015 NAS-101586: Add configurables to ixnas entry in "Available VFS Module…
  userguide/sharing.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1019 NAS-101587: Rewrite System Dataset text about storing system logs.
  userguide/system.rst
Labels: FN/TN, Master

#1020 NAS-101587: Rewrite System Dataset text about storing system logs.
  userguide/system.rst
Labels: 11.2-U5, 11.2-legacy, FN/TN

#1021 NAS-101587: Rewrite System Dataset text about storing system logs and…
  userguide/system.rst
Labels: Angulargui, FN/TN

#1022 NAS-101587: Rewrite System Dataset text about storing system logs and…
  userguide/system.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1027 NAS-101289 TrueNAS 11.2-U4: Add alert to alertevents.rst for disk mismatch with HA co…
  userguide/snippets/alertevents.rst
Labels: Master, TrueNAS

#1028 NAS-101289 TrueNAS 11.2-U4: Add alert to alertevents.rst for disk mismatch with HA co…
  userguide/snippets/alertevents.rst
Labels: 11.2-legacy, TrueNAS

#1033 Update intro for new "Crash reporting" field.
  userguide/intro.rst
Labels: FN/TN, Master

#1037 Add new "Crash reporting" field to intro.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#1038 NAS-100504: Add intro entry for one-shot alerts.
  userguide/intro.rst
Labels: Angulargui, FN/TN

#1039 NAS-101294 Remove fields from Directory Services > Active Directory
  userguide/directoryservices.rst
  userguide/intro.rst
Labels: Angulargui, FN/TN

#1040 NAS-100322: Add new FC HBA alert to alertevents.rst
  userguide/snippets/alertevents.rst
Labels: Master, TrueNAS

#1041 NAS-100322: Add new FC HBA alert to alertevents.rst
  userguide/snippets/alertevents.rst
Labels: 11.2-legacy, TrueNAS

#1043 NAS-100572: Update Network/Global Config/Hostname (Virtual) descripti…
  userguide/network.rst
Labels: Master, TrueNAS

#1044 NAS-100572: Update Network/Global Config/Hostname (Virtual) descripti…
  userguide/network.rst
Labels: 11.2-legacy, TrueNAS

#1048 NAS-100716: Remove TrueNAS note about alert if system dataset is not …
  userguide/system.rst
Labels: 11.1-truenas, TrueNAS

#1054 NAS-100148: Expand text about what is described in the BSGs.
  userguide/tn_hardware.rst
Labels: Master, TrueNAS

#1046 NAS-100716: Remove TrueNAS note about alert if system dataset is not …
  userguide/system.rst
Labels: Master, TrueNAS

#1047 NAS-100716: Remove TrueNAS note about alert if system dataset is not …
  userguide/system.rst
Labels: 11.2-legacy, TrueNAS

#1049 NAS-100716: Remove TrueNAS note about system datasets.
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1062 Fix up note removal.
  userguide/system.rst
Labels: Master, TrueNAS

#1064 NAS-100496 Update System>General screenshot for FN and TN
  userguide/images/system-general.png
  userguide/images/tn_system-general.png
Labels: FN/TN, Master

#1068 TN screenshots: Sharing chapter
  userguide/images/afp9a.png
  userguide/images/grow1.png
  userguide/images/tn_afp2a.png
  userguide/images/tn_fibre1.png
  userguide/images/tn_fibre2.png
  userguide/images/tn_grow.png
  userguide/images/tn_system-tunables-npiv.png
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#1069 TN screenshots: Sharing Chapter
  userguide/images/afp9a.png
  userguide/images/grow1.png
  userguide/images/tn_afp2a.png
  userguide/images/tn_fibre1.png
  userguide/images/tn_fibre2.png
  userguide/images/tn_grow.png
  userguide/images/tn_system-tunables-npiv.png
  userguide/sharing.rst
Labels: FN/TN, Master

#1065 NAS-101771 Update api section for TrueNAS
  userguide/api.rst
  userguide/images/apiv2.png
Labels: 11.2-legacy

#1072 TN review: account and network section
  userguide/account.rst
  userguide/network.rst
Labels: 11.2-legacy, FN/TN

#1073 TN review: account and network sections
  userguide/account.rst
  userguide/network.rst
Labels: FN/TN, Master

#1066 NAS-101771: Review tn_initial.rst for TrueNAS 11.2-U4 release
  userguide/images/tn_BIOS1.png
  userguide/images/tn_BIOS2.png
  userguide/images/tn_BIOS3.png
  userguide/images/tn_BIOS4.png
  userguide/images/tn_BIOS5.png
  userguide/images/tn_BIOS6.png
  userguide/images/tn_IPMI_console_show.png
  userguide/images/tn_IPMIaccept.png
  userguide/images/tn_IPMIcontinue.png
  userguide/images/tn_IPMIdownload.png
  userguide/images/tn_IPMIjava.png
  userguide/images/tn_IPMIlogin.png
  userguide/images/tn_login.png
  userguide/images/tn_login1c.png
  userguide/images/tn_webinterface.png
  userguide/network.rst
  userguide/tn_initial.rst
Labels: 11.2-legacy, TrueNAS

#1067 Cherry-pick #1066: Review tn_initial.rst for TrueNAS 11.2-U4
  userguide/images/tn_BIOS1.png
  userguide/images/tn_BIOS2.png
  userguide/images/tn_BIOS3.png
  userguide/images/tn_BIOS4.png
  userguide/images/tn_BIOS5.png
  userguide/images/tn_BIOS6.png
  userguide/images/tn_IPMI_console_show.png
  userguide/images/tn_IPMIaccept.png
  userguide/images/tn_IPMIcontinue.png
  userguide/images/tn_IPMIdownload.png
  userguide/images/tn_IPMIjava.png
  userguide/images/tn_IPMIlogin.png
  userguide/images/tn_login.png
  userguide/images/tn_login1c.png
  userguide/images/tn_webinterface.png
  userguide/network.rst
  userguide/tn_initial.rst
Labels: Master, TrueNAS

#1070 NAS-101771: Review console_menu.rst and related image
  userguide/snippets/console_menu.rst
Labels: 11.2-legacy, FN/TN

#1071 NAS-101771: Review console_menu.rst and related image
  userguide/snippets/console_menu.rst
Labels: FN/TN, Master

#1074 TN review: Storage section
  userguide/images/disk.png
  userguide/images/replication4.png
  userguide/images/replication6.png
  userguide/images/storage-detach.png
  userguide/images/view.png
  userguide/install.rst
  userguide/storage.rst
  userguide/wizard.rst
Labels: 11.2-legacy, FN/TN

#1075 TrueNAS 11.2U4 review: system.rst
  userguide/images/system-alertservices-add.png
  userguide/images/system-certs-manage1.png
  userguide/images/system-import-ca.png
  userguide/images/system-import-cert.png
  userguide/images/system-information.png
  userguide/images/tn_be2.png
  userguide/images/tn_system-advanced.png
  userguide/images/tn_system-alerts.png
  userguide/images/tn_system-boot.png
  userguide/images/tn_system-ca.png
  userguide/images/tn_system-cert.png
  userguide/images/tn_system-cloud-credentials.png
  userguide/images/tn_system-email.png
  userguide/images/tn_system-failover.png
  userguide/images/tn_system-general.png
  userguide/images/tn_system-information.png
  userguide/images/tn_system-proactive-support.png
  userguide/images/tn_system-support.png
  userguide/images/tn_system-system-dataset.png
  userguide/images/tn_system-update.png
  userguide/images/tn_system-view-enclosure.png
  userguide/system.rst
Labels: 11.2-legacy, FN/TN

#1076 Port PR 1075 to master
  userguide/images/system-alertservices-add.png
  userguide/images/system-certs-manage1.png
  userguide/images/system-import-ca.png
  userguide/images/system-import-cert.png
  userguide/images/system-information.png
  userguide/images/tn_be2.png
  userguide/images/tn_system-advanced.png
  userguide/images/tn_system-alerts.png
  userguide/images/tn_system-boot.png
  userguide/images/tn_system-ca.png
  userguide/images/tn_system-cert.png
  userguide/images/tn_system-cloud-credentials.png
  userguide/images/tn_system-email.png
  userguide/images/tn_system-failover.png
  userguide/images/tn_system-information.png
  userguide/images/tn_system-proactive-support.png
  userguide/images/tn_system-support.png
  userguide/images/tn_system-system-dataset.png
  userguide/images/tn_system-update.png
  userguide/images/tn_system-view-enclosure.png
  userguide/system.rst
Labels: FN/TN, Master

#1077 NAS-101771: TN 11.2-U4.1 review Upgrading a ZFS Pool
  userguide/images/pool1.png
  userguide/snippets/upgradingazfspool.rst
Labels: 11.2-legacy, FN/TN

#1078 NAS-101771: TN 11.2-U4.1 review Upgrading a ZFS Pool
  userguide/images/pool1.png
  userguide/snippets/upgradingazfspool.rst
Labels: FN/TN, Master

#1079 TN review: Storage section
  userguide/images/disk.png
  userguide/images/replication4.png
  userguide/images/replication6.png
  userguide/images/storage-detach.png
  userguide/images/view.png
  userguide/install.rst
  userguide/storage.rst
  userguide/wizard.rst
Labels: FN/TN, Master

#1045 Add security issue info when using "allow_raw_sockets".
  userguide/jails.rst
Labels: Angulargui, FN/TN

#1080 TN review: Services section
  userguide/images/ftp1.png
  userguide/images/rsyncd.png
  userguide/images/services-afp.png
  userguide/images/services-asigra.png
  userguide/images/smart2.png
  userguide/images/tftp.png
  userguide/images/tn_cifs1b.png
  userguide/images/tn_services.png
  userguide/services.rst
Labels: 11.2-legacy, FN/TN

#1081 NAS-101771: Review tasks.rst for TrueNAS 11.2-U4.1
  userguide/images/cloudsync-example-cropped.png
  userguide/images/rsync2.png
  userguide/images/tn_tasks-cloudsync.png
  userguide/tasks.rst
Labels: 11.2-legacy, FN/TN

#1082 NAS-101771: Review tasks.rst for TrueNAS 11.2-U4.1
  userguide/images/cloudsync-example-cropped.png
  userguide/images/rsync2.png
  userguide/images/tn_tasks-cloudsync.png
  userguide/tasks.rst
Labels: FN/TN, Master

#1083 NAS-101771: review directoryservice.rst for TN 11.2-U4.1
  userguide/directoryservice.rst
Labels: 11.2-legacy, FN/TN

#1084 NAS-101771: review directoryservice.rst for TN 11.2-U4.1
  userguide/directoryservice.rst
Labels: FN/TN, Master

#1085 Port User Quota Administration section into sharing.rst to fix build warning
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#1086 NAS-100087 , NAS-101289 : TrueNAS disk number mismatches
  userguide/snippets/alertevents.rst
  userguide/system.rst
Labels: Master, TrueNAS

#1087 NAS-100087 , NAS-101289 : TrueNAS disk mismatches
  userguide/snippets/alertevents.rst
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1088 NAS-100087 , NAS-101289 : TrueNAS disk mismatches
  userguide/snippets/alertevents.rst
  userguide/system.rst
Labels: 11.2-legacy, TrueNAS

#1089 TN review: Services section
  userguide/images/ftp1.png
  userguide/images/rsyncd.png
  userguide/images/services-afp.png
  userguide/images/services-asigra.png
  userguide/images/smart2.png
  userguide/images/tftp.png
  userguide/images/tn_cifs1b.png
  userguide/images/tn_services.png
  userguide/services.rst
Labels: FN/TN, Master

#1090 NAS-100386 : Rework TrueNAS only text about alert messages generated …
  userguide/snippets/alertevents.rst
Labels: Master, TrueNAS

#1091 NAS-100386 : Rework TrueNAS only text about alert messages generated …
  userguide/snippets/alertevents.rst
Labels: Angulargui, TrueNAS

#1092 NAS-100386 : Rework TrueNAS only text about alert messages generated …
  userguide/snippets/alertevents.rst
Labels: 11.2-legacy, TrueNAS

#1093 NAS-100410 : Add NVDIMM alert to alertevents.rst
  userguide/snippets/alertevents.rst
Labels: Master, TrueNAS

#1094 NAS-100410 : Add NVDIMM alert to alertevents.rst
  userguide/snippets/alertevents.rst
Labels: Angulargui, TrueNAS

#1095 NAS-100410 : Add NVDIMM alert to alertevents.rst
  userguide/snippets/alertevents.rst
Labels: 11.2-legacy, TrueNAS

#1096 NAS-100410 : Add NVDIMM alert to alertevents.rst
  userguide/snippets/alertevents.rst
Labels: 11.1-truenas, TrueNAS

#1099 NAS-100987 : Manually port Asigra text to unify elements and add 11.1…
  userguide/images/services-asigra.png
  userguide/services.rst
  userguide/snippets/trademarks.rst
Labels: 11.1-truenas, FN/TN

#1100 NAS-100716: Re-verify TrueNAS 11.3 behavior and unify system dataset …
  userguide/system.rst
Labels: FN/TN, Master

#1101 NAS-100148: Expand text about what is described in the BSGs.
  userguide/tn_hardware.rst
Labels: 11.1-truenas, TrueNAS

#1102 NAS-100148: Expand text about what is described in the BSGs.
  userguide/tn_hardware.rst
Labels: 11.2-legacy, TrueNAS

#1103 NAS-100148: Expand text about what is described in the BSGs.
  userguide/tn_hardware.rst
Labels: Angulargui, TrueNAS

#1104 RM 9053: Add missing "Time Machine Quota" field to sharing.rst
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#1105 RM 9053: Add missing "Time Machine Quota" field to sharing.rst
  userguide/sharing.rst
Labels: FN/TN, Master

#1106 RM 9053: Add missing "Time Machine Quota" field to sharing.rst
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#1107 RM 9053: Add missing "Time Machine Quota" field to sharing.rst
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN

#1097 NAS-100987 : Update Asigra documentation
  userguide/services.rst
  userguide/snippets/trademarks.rst
Labels: 11.2-legacy, FN/TN

#1098 NAS-100987 : Update Asigra documentation
  userguide/services.rst
  userguide/snippets/trademarks.rst
Labels: FN/TN, Master

#1111 redmine 27384 fix (angulargui)
  userguide/jails.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN

#1113 58083: Inspect FreeNAS and TrueNAS systems installed with 11.2 U4, co…
  userguide/directoryservice.rst
Labels: 11.2-legacy, FN/TN
