Repository freenas/freenas-docs, pull requests merged in 2019-06, with the labels that each got.

#1108 NAS-101234: Add text about CARP status alert to system.rst and alertevents.rst
  userguide/system.rst
Labels: 11.2-legacy, Ready to Merge, TrueNAS

#1109 NAS-101234: Add text about CARP status alert to system.rst and alertevents.rst
  userguide/system.rst
Labels: Master, Ready to Merge, TrueNAS

#1135 NAS-100122: Replace all textual uses of the terms "node" and "storage controller"
  userguide/conf.py
  userguide/directoryservices.rst
  userguide/network.rst
  userguide/services.rst
  userguide/snippets/alertevents.rst
  userguide/snippets/console_menu.rst
  userguide/storage.rst
  userguide/system.rst
  userguide/tn_initial.rst
  userguide/tn_options.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1136 Nas100122 node term update master
  userguide/conf.py
  userguide/directoryservice.rst
  userguide/network.rst
  userguide/services.rst
  userguide/snippets/alertevents.rst
  userguide/snippets/console_menu.rst
  userguide/storage.rst
  userguide/system.rst
  userguide/tn_initial.rst
  userguide/tn_options.rst
Labels: 11.3 Beta 1, Master, TrueNAS

#1115 58083: Manually port relevant changes to 11.2-angular branch
  userguide/directoryservices.rst
Labels: 11.2-angular, FN/TN

#1121 28566: Update Hostname descriptions in Network/Global Configuration S…
  userguide/network.rst
Labels: 11.2-legacy, FN/TN

#1124 28566: Update Hostname descriptions in Network/Global Configuration S…
  userguide/network.rst
Labels: 11.2-angular, FN/TN

#1125 NAS-100987 : Update Asigra documentation
  userguide/images/truenas/services-asigra.png
  userguide/services.rst
  userguide/snippets/trademarks.rst
Labels: Angulargui, TrueNAS

#1127 NAS-101545: Add FreeNAS changelog note about Python version update.
  userguide/intro.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1128 NAS-101545: Add FreeNAS changelog note about Python version update.
  userguide/intro.rst
Labels: 11.2-U5, 11.2-legacy, FN/TN

#1142 NAS-101890: Add text about RESET LAYOUT button and rework SUGGEST LAYOUT button text
  userguide/images/storage-pools-add.png
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1143 NAS-101890: Add text about RESET LAYOUT button and rework SUGGEST LAYOUT button text
  userguide/storage.rst
Labels: 11.2-U5, Angulargui, FN/TN

#1144 NAS-101760: Update Jail name description to indicate that periods are…
  userguide/jails.rst
Labels: 11.2-U5, Angulargui, FN/TN

#1145 NAS-101760: Update Jail name description to indicate that periods are…
  userguide/jails.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1146 NAS-101725: Add TrueNAS ifdef about rebooting the passive |node| afte…
  userguide/system.rst
Labels: 11.2-U5, Master, TrueNAS

#1147 NAS-101725: Add TrueNAS ifdef about rebooting the passive |node| afte…
  userguide/system.rst
Labels: 11.2-U5, 11.2-legacy, TrueNAS

#1150 NAS-101971: Add asigra plugin to iX plugin index
  userguide/intro.rst
  userguide/plugins.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1151 NAS-101971: Add Asigra to iX Plugin index
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1110 redmine 27384 fix (master)
  userguide/storage.rst
Labels: FN/TN, Master

#1112 redmine 27384 fix (11.2-angular)
  userguide/storage.rst
Labels: 11.2-angular, FN/TN

#1114 redmine 27384 fix (11.2-legacy)
  userguide/storage.rst
Labels: 11.2-legacy, FN/TN

#1117 redmine 27700 fix (master)
  userguide/snippets/alertevents.rst
Labels: FN/TN, Master

#1118 redmine 27700 fix (11.2-legacy)
  userguide/snippets/alertevents.rst
Labels: 11.2-legacy, FN/TN

#1119 redmine 27700 fix (angulargui)
  userguide/snippets/alertevents.rst
Labels: Angulargui, FN/TN

#1120 redmine 27700 fix (11.2-angular)
  userguide/snippets/alertevents.rst
Labels: 11.2-angular, FN/TN

#1131 NAS-101655 Remove installing and upgrading note.
  userguide/install.rst
Labels: Angulargui, FN/TN

#1132 NAS-101655 Remove installing and upgrading note.
  userguide/install.rst
Labels: 11.2-angular, FN/TN

#1133 NAS-101802 Add intro for updated AMD driver.
  userguide/intro.rst
Labels: 11.2-legacy, FN/TN

#1134 NAS-101802 Add intro for updated AMD driver.
  userguide/intro.rst
Labels: 11.2-angular, FN/TN

#1148 NAS-101759 Add instructions and docs about changing passphrase for a pool
  userguide/storage.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1126 redmine 27384 fix (angulargui). Updated with Tim feedback.
  userguide/storage.rst
Labels: Angulargui, FN/TN

#1116 58083: Update LDAP Config Options table to match what is visible on 11.3 TrueNAS/FreeNAS
  userguide/directoryservice.rst
Labels: FN/TN, Master

#1122 28566: Update Hostname descriptions in Network/Global Configuration S…
  userguide/network.rst
Labels: FN/TN, Master

#1123 28566: Update Hostname descriptions in Network/Global Configuration S…
  userguide/network.rst
Labels: Angulargui, FN/TN

#1139 NAS-101639: Add noacl VFS module to "Available VFS Modules" table
  userguide/intro.rst
  userguide/sharing.rst
Labels: 11.2-legacy, FN/TN

#1140 NAS-101639: Add noacl VFS module and add note to U5 changelog
  userguide/intro.rst
  userguide/sharing.rst
Labels: 11.2-angular, FN/TN

#1152 NAS-101880 add intro for replication log files being moved
  userguide/intro.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1153 NAS-101880 add intro for replication log files being moved
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1149 NAS-100967 docs for naming a cloned VM
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1141 NAS-100846: rewrite replication documentation
  userguide/conf.py
  userguide/images/system-ssh-connections-add.png
  userguide/images/system-ssh-keypairs-add.png
  userguide/images/tasks-replication-add-advanced.png
  userguide/images/tasks-replication-add-wizard-snapshots.png
  userguide/images/tasks-replication-add-wizard-ssh.png
  userguide/images/tasks-replication-tasks-manual-complete.png
  userguide/images/tasks-replication-tasks-manual-key.png
  userguide/images/tasks-replication-tasks-semiauto-complete.png
  userguide/images/tasks-replication-tasks-semiauto-snapshot.png
  userguide/images/tasks-replication-tasks-semiauto-token.png
  userguide/images/tasks-replication-tasks-semiauto.png
  userguide/intro.rst
  userguide/system.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1156 NAS-101234: Add note about HA Carp behavior
  userguide/system.rst
Labels: 11.2-U5, Angulargui, TrueNAS

#1157 NAS-100122: Clean up a couple more spots where node/storage controlle…
  userguide/network.rst
  userguide/storage.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Master, TrueNAS

#1158 NAS-100122: Clean up a couple more spots where node/storage controlle…
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1159 NAS-100987: Add Asigra entry to list at beginning of services.rst
  userguide/services.rst
Labels: 11.2-U5, Angulargui, TrueNAS

#1160 NAS-101725: fix term replacement that got backported to 11.2 branch b…
  userguide/system.rst
Labels: 11.2-U5, 11.2-legacy, TrueNAS

#1154 NAS-101516 Remove docs for "Periodic Notification User" field.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1155 NAS-101516 Remove docs for "Periodic Notification User" field.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1162 NAS-101771: Fix replacement error between angulargui and master branches
  userguide/directoryservices.rst
Labels: 11.2-U5, Angulargui, TrueNAS

#1163 NAS-101639: Add noacl VFS module
  userguide/sharing.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1164 NAS-101639: Add noacl VFS module
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1167 NAS-100121: Begin Replication/SSH Connections/SSH Keypairs/Periodic Snapshot tasks rewrite
  userguide/conf.py
  userguide/images/replication1c.png
  userguide/images/replication3a.png
  userguide/images/replication5.png
  userguide/images/replication6.png
  userguide/images/replication7.png
  userguide/images/replication8.png
  userguide/images/replication9a.png
  userguide/images/storage-periodic-snapshot.png
  userguide/images/storage-replication-add.png
  userguide/images/storage-replication-tasks.png
  userguide/images/system-ssh-connections-add.png
  userguide/images/system-ssh-keypairs-add.png
  userguide/intro.rst
  userguide/storage.rst
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1165 Move amd temp monitor to correct intro section
  userguide/intro.rst
Labels: 11.2-U5, 11.2-legacy, FN/TN

#1166 Move amd temp monitor to correct intro section
  userguide/intro.rst
Labels: 11.2-U5, 11.2-angular, FN/TN

#1172 NAS-102026 Add docs about "Export Pool Encryption Keys" setting.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1173 add location of replication logs
  userguide/storage.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1175 add location of replication logs
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1176 NAS-101725: cherry-pick TrueNAS system dataset reboot text to angulargui
  userguide/system.rst
Labels: 11.2-U5, Angulargui, FN/TN

#1181 NAS-101924 add intro entry for 'minutes' field in Periodic Snapshot Tasks>ADD
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1184 NAS-102062 mention certain names are reserved for smb shares.
  userguide/intro.rst
  userguide/sharing.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1183 Fix truenas build errors.
  userguide/services.rst
  userguide/sharing.rst
  userguide/snippets/alertevents.rst
  userguide/storage.rst
Labels: 11.2-angular, TrueNAS

#1185 NAS-102062 mention certain names are reserved for smb shares.
  userguide/intro.rst
  userguide/sharing.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1197 NAS-102147: Add text about OAuth with Cloud Providers.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.2-U5, 11.2-legacy

#1210 NAS-102147: Add text about OAuth with Cloud Providers.
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1161 NAS-101830 Update network>interface>ADD table of options.
  userguide/network.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1168 NAS-102057 Add link to manual update files
  userguide/system.rst
Labels: FN/TN, Master

#1177 NAS-100336 Add docs for cloud sync stop button
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1182 NAS-101827 Add docs for 'Export encrypted pools geli keys' option.
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1187 NAS-102059 add docs for "Usage Collection" option
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1178 NAS-102018 Add docs for cloud sync stop button
  userguide/intro.rst
  userguide/tasks.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1169 NAS-102057 Add link to manual update files
  userguide/system.rst
Labels: 11.2-legacy, FN/TN

#1170 NAS-102057 Add link to manual update files
  userguide/system.rst
Labels: Angulargui, FN/TN

#1171 NAS-102057 Add link to manual update files
  userguide/system.rst
Labels: 11.2-angular, FN/TN

#1189 NAS-101550 update jail docs with new options
  userguide/intro.rst
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1186 NAS-101906 add docs for "usage collection" option
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1190 NAS-101947 sync naming criteria between group name and user name
  userguide/account.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1191 NAS-101947 sync naming criteria between group name and user name
  userguide/accounts.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1192 NAS-101206 add note about adding more ip addresses to jails
  userguide/jails.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1193 NAS-101247 docs on viewing logs of replication tasks
  userguide/tasks.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1195 NAS-101530 remove 'unix extensions' docs
  userguide/directoryservice.rst
Labels: 11.3 Beta 1, FN/TN, Master

#1196 NAS-100487 add intro entry for restarting jails in UI.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1220 NAS-101177: Add 'Name' field to Replication Tasks
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1221 NAS-101274: Add 'Hold Pending Snapshots' field to replication tasks.
  userguide/intro.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN

#1198 88182 and 88585: Add new Gold Support phone number and update Support hours
  userguide/tn_intro.rst
Labels: 11.3 Beta 1, Master, TrueNAS

#1199 88182 and 88585: Add new Gold Support phone number and update Support hours
  userguide/snippets/contact.rst
  userguide/tn_intro.rst
Labels: 11.3 Beta 1, Angulargui, TrueNAS

#1200 88182 and 88585: Add new Gold Support phone number and update Support hours
  userguide/tn_intro.rst
Labels: 11.2-U5, 11.2-legacy, TrueNAS

#1201 88182 and 88585: Add new Gold Support phone number and update Support hours
  userguide/tn_intro.rst
Labels: 11.2-U5, 11.2-angular, TrueNAS

#1205 88182 and 88585: Add new Gold Support phone number and update Support hours
  userguide/snippets/contact.rst
Labels: 11.1-truenas, TrueNAS

#1188 NAS-101381 Update docs for new plugins page.
  userguide/Makefile
  userguide/conf.py
  userguide/intro.rst
  userguide/plugins.rst
Labels: 11.3 Beta 1, Angulargui, FN/TN
