Repository freenas/freenas-docs, pull requests merged in 2019-03, with the labels that each got.

#718 75325: Add note about configuring OOB Enternet port IP.
  userguide/snippets/xseries.rst
Labels: BSG, FN/TN, Master

#720 69607: Add note about common rclone sync with dropbox error.
  userguide/tasks.rst
Labels: FN/TN, Master

#693 Match the labels the userguide for VM wizard options to labels in web UI
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#723 69607: Add note about common rclone sync with dropbox error.
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#724 75289 (TrueNAS 11.2-U3): Add warning box pointing to X-Series out-of-…
  userguide/snippets/xseries.rst
  userguide/tn_initial.rst
Labels: Master, Ready to Merge, TrueNAS

#725 75289 (TrueNAS 11.2-U3): Add warning box pointing to X-Series out-of-…
  userguide/snippets/xseries.rst
  userguide/tn_initial.rst
Labels: Angulargui, BSG, Ready to Merge, TrueNAS

#730 27864 (TrueNAS 11.2-U3): Add instruction to use physical interface IP addressses only w…
  userguide/sharing.rst
Labels: Master, Ready to Merge, TrueNAS

#731 27864 (TrueNAS 11.2-U3): Add instruction to use physical interface IP addressses only w…
  userguide/sharing.rst
Labels: Angulargui, Ready to Merge, TrueNAS

#733 remove 3 tunables from the truenas part.
  userguide/system.rst
Labels: Angulargui, FN/TN

#737 73650: Update "Access Based Share Enumeration" field description
  userguide/sharing.rst
Labels: FN/TN, Master

#744 Made change so 'securelevel' matched the choices in drop-down.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#738 75873: Document new shadow_copy_zfs VFS object.
  userguide/intro.rst
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#739 75873: Document new shadow_copy_zfs VFS object.
  userguide/intro.rst
  userguide/sharing.rst
Labels: FN/TN, Master

#741 Updated text to reflect the button change. Other text fixes.
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#743 Updated sftp field requirement wording. It changed from an 'and' to 'or'
  userguide/system.rst
Labels: Angulargui, FN/TN

#736 73650: Add new entry for "Access Based Share Enumeration" checkbox in…
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#746 70858: Clear up the endpoint URL description.
  userguide/system.rst
Labels: Angulargui, FN/TN

#750 65214: Add text for refresh button on updates page.
  userguide/Makefile
  userguide/conf.py
  userguide/system.rst
Labels: Angulargui, FN/TN

#740 72529: Minor change to snapshot rollback description and add entry to intro.rst
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN, Ready to Merge

#742 71013, 67305, 69672, 69681: Update VM wizard field descriptions and add new entry to Docke…
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN, Ready to Merge

#747 69186: Update LUN ID field description
  userguide/sharing.rst
Labels: Angulargui, FN/TN, Ready to Merge

#748 69186: Update LUN ID field description
  userguide/sharing.rst
Labels: FN/TN, Master, Ready to Merge

#749 62874: Create 'Network Summary' section.
  userguide/network.rst
Labels: Angulargui, FN/TN

#752 75675: Add "Host" field to TFTP Configuration Options table:
  userguide/intro.rst
  userguide/services.rst
Labels: Angulargui, FN/TN

#753 60822: Add "Host" field to TFTP Configuration Options table:
  userguide/intro.rst
  userguide/services.rst
Labels: FN/TN, Master

#754 72553: Added and updated text with an unlock and lock glyph.
  userguide/Makefile
  userguide/conf.py
  userguide/storage.rst
Labels: Angulargui, FN/TN

#758 71939: Update description of Encryption Mode field in the Active Dire…
  userguide/directoryservice.rst
Labels: FN/TN, Master

#759 71939: Update description of Encryption Mode field in the Active Dire…
  userguide/directoryservices.rst
Labels: Angulargui, FN/TN

#761 74938: Add warning about trying to configure Domain Controller when A…
  userguide/directoryservices.rst
  userguide/intro.rst
  userguide/services.rst
Labels: Angulargui, FN/TN

#762 76701: Add Restart option to a Running VM.
  userguide/intro.rst
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#766 74056: Updated email security options in the table.
  userguide/system.rst
Labels: Angulargui, FN/TN

#767 65754: bits -> megabytes for graphs in Reporting > Network.
  userguide/intro.rst
  userguide/reporting.rst
Labels: Angulargui, FN/TN

#768 69076: Small change to include the ticket URL after creating in System>Support.
  userguide/system.rst
Labels: Angulargui, FN/TN

#777 Port note about cloud sync times to angular branch.
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#764 70527: Port Multipath text improvements to master
  userguide/storage.rst
Labels: FN/TN, Master, Ready to Merge

#755 31986: Update UPS table to match the new field functionality.
  userguide/services.rst
Labels: Angulargui, FN/TN

#769 71038: Update description of what is displayed in jails table.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#770 71619: Update zvol delete text to include snapshots.
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN

#771 71619: Update zvol delete text to include snapshots.
  userguide/storage.rst
Labels: FN/TN, Master

#772 11.2-U3 screenshots: manual updates
  userguide/images/alert-example.png
  userguide/images/installer-install-menu.png
  userguide/images/network-link-aggregations-edit.png
  userguide/images/network-link-aggregations-members-add.png
  userguide/images/network-link-aggregations-members.png
  userguide/images/storage-pools-encrypt-passphrase.png
  userguide/images/system-boot-attach.png
  userguide/images/system-boot-mirror.png
  userguide/images/system-update.png
Labels: Angulargui, FN/TN

#773 11.2-U3 Screenshots: manual updates
  userguide/images/install2c.png
Labels: FN/TN, Master

#774 76531: Add text explaining disabling SMART on a disk also disables di…
  userguide/services.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN

#757 58437: Add entry for new CPU temperature graphs.
  userguide/intro.rst
  userguide/reporting.rst
Labels: Angulargui, FN/TN, Ready to Merge

#779 71619: Update zvol delete description.
  userguide/storage.rst
Labels: FN/TN, Master

#778 71619: Remove zvol snapshot delete entry from intro.rst.
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN, Ready to Merge

#760 61785: Remove mention of pool column in Storage > Disks section
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN, Ready to Merge

#763 70527: Rework Storage > Multipaths text
  userguide/intro.rst
  userguide/storage.rst
Labels: Angulargui, FN/TN

#756 69688: Update the 'Bind' field descrip. for VMs.
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#765 59649: Update text to include the new slider bar for VMs.
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#775 76531: Add text explaining disabling SMART also disables disk temperature reporting
  userguide/services.rst
  userguide/storage.rst
Labels: FN/TN, Master, Ready to Merge

#780 80679 & 77089: Mention init/shutdown scripts use 'sh' not the default 'zsh'
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#783 76531: Sync with PR #775
  userguide/storage.rst
Labels: Angulargui, FN/TN, Ready to Merge

#781 76386: Update SMB Share Options table to expand Path and Name field d…
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#782 76386: Update SMB Share Options table to expand Path and Name field d…
  userguide/sharing.rst
Labels: FN/TN, Master

#784 69186: Expand LUN ID description
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#785 69186: Expand LUN ID description
  userguide/sharing.rst
Labels: FN/TN, Master
