Repository freenas/freenas-docs, pull requests merged in 2019-12, with the labels that each got.

#1605 NAS-103536: Document plugin startup behavior
  userguide/plugins.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1621 NAS-103124: Add NAT Forwards fields and descriptions to advanced jail…
  userguide/jails.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1616 DOCS-70: Add pgp key verification instructions to install chapter
  userguide/install.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1628 DOCS-78: Add text about ACL inheritance
  userguide/storage.rst
Labels: Angulargui, FN/TN

#1622 NAS-103882 Clarify docs on clone snapshot behavior. sync with helptext.
  userguide/storage.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1629 NAS-101498: Add description of parallel replication behavior to intro.
  userguide/intro.rst
Labels: 11.3 RC1, Angulargui

#1632 DOCS-85: Update one screenshot title and add RC1 installer image
  userguide/images/console/installer-install-menu.png
  userguide/plugins.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1631 DOCS-83 Update broken links in zfs primer.
  userguide/zfsprimer.rst
Labels: 11.3 RC1, Angulargui, FN/TN

#1590 NAS-102085: Update one-time replication behavior for Replication Wiza…
  userguide/tasks.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1633 DOCS-99: Rewrite SMB "Configuring Authenticated Access with Local Use…
  userguide/images/sharing-windows-smb-dataset-acl.png
  userguide/sharing.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1630 DOCS-88: Rewrite TN HA update procedure for 11.3
  userguide/conf.py
  userguide/system.rst
Labels: 11.3 RC2, Angulargui, TrueNAS

#1634 DOCS-90: Update TrueNAS guide to use correct active/standby controlle…
  userguide/conf.py
  userguide/directoryservices.rst
  userguide/services.rst
  userguide/snippets/alertevents.rst
  userguide/snippets/ui_login.rst
  userguide/storage.rst
  userguide/system.rst
  userguide/tn_options.rst
Labels: Angulargui, TrueNAS

#1637 NAS-103508: Update description of System/Cloud Credentials/SFTP fields
  userguide/system.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1636 NAS-103507: Update replication section intro:
  userguide/tasks.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1638 NAS-103508: Unify text between docs and webui help text.
  userguide/system.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1635 NAS-104229 Remove docs for account entry in gear settings
  userguide/settings.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1639 NAS-103141: Update TrueNAS Failover section
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1642 NAS-103956 add docs for reverting/changing SED drive data and passwords.
  userguide/system.rst
Labels: Angulargui, FN/TN

#1641 NAS-103567: Update SED documentation
  userguide/system.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1643 NAS-104069: Update HA update process slightly
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1645 NAS-103535: Update Onedrive credential docs.
  userguide/system.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1647 NAS-103592: Update Services/UPS/Port or Hostname field description
  userguide/intro.rst
  userguide/services.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1649 DOCS-88: Clarify HA update controller order.
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1650 NAS-103716: Update Tasks/Cloud Sync Tasks/Direction description
  userguide/tasks.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1640 NAS-104007 update docs for new iocage pool activation dialog.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#1653 NAS-104040 Clarify min and max poll docs.
  userguide/system.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1651 NAS-103956 add instructions for reset data/passwords for SED.
  userguide/system.rst
Labels: Angulargui, FN/TN

#1655 NAS-103595: Update procedure to temporarily apply network settings and then permanantly apply them.
  userguide/network.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1656 NAS-103557 Add docs for human readable field in VMs.
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#1661 NAS-103854: Update iSCSI Wizard Portal page text:
  userguide/sharing.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1657 NAS-103998 Clarify password toggle docs.
  userguide/settings.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1644 NAS-103887 add docs for saving iocage config to new boot environments.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#1659 NAS-103807: Update Replication Wizard snapshot process:
  userguide/tasks.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1654 NAS-103604 Update process to destroy pool and data in docs
  userguide/storage.rst
Labels: Angulargui, FN/TN

#1662 NAS-104119 Add docs for "NAT Interface" field for jails.
  userguide/jails.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1664 NAS-104220: Update Advanced Replication Options table
  userguide/tasks.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1660 NAS-103439 docs for displaying plugin Admin Portals.
  userguide/plugins.rst
Labels: Angulargui, FN/TN

#1663 NAS-104321: Update ACL management text:
  userguide/storage.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1665 NAS-104280: Sync LDAP field descriptions with UI help text
  userguide/directoryservices.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1666 NAS-104526: Add warning about deleting the last per. snap task that i…
  userguide/tasks.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1668 NAS-102315 docs for VMs are licensed feature only on TN.
  userguide/truenas.rst
  userguide/virtualmachines.rst
Labels: TrueNAS

#1669 NAS-104231 sync allow repeated GIDs helptext with guide.
  userguide/accounts.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1670 NAS-104052 sync docs with dataset quota 'Inherit' alert helptext.
  userguide/storage.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1671 NAS-103887 Clarify docs on jail config backup location.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#1672 NAS-104009: Sync update jail/plugin "Name" description from UI text.
  userguide/jails.rst
  userguide/plugins.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1673 NAS-103887 clarify jail/plugin config backup.
  userguide/jails.rst
Labels: Angulargui, FN/TN

#1658 NAS-103404 add docs for human readable field "memory" in VMs.
  userguide/conf.py
  userguide/snippets/usingui.rst
  userguide/tasks.rst
  userguide/virtualmachines.rst
Labels: Angulargui, FN/TN

#1676 DOCS-109: Remove show tracebacks option from System/Advanced
  userguide/intro.rst
  userguide/system.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1674 DOCS-113: Add recommendations about Hardware Offload to jails and VMs.
  userguide/jails.rst
  userguide/virtualmachines.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1675 DOCS-116: Update iSCSI Portal IP Addresses descriptions.
  userguide/sharing.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1677 DOCS-115 Update system>reporting docs.
  userguide/system.rst
  userguide/tasks.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1679 DOCS-120 update docs for MTU network>interfaces.
  userguide/network.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1681 DOCS-114: New alert for slow pool I/O
  userguide/intro.rst
  userguide/snippets/alertevents.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1680 DOCS-121: Update Storage/Disks options
  userguide/intro.rst
  userguide/storage.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1683 DOCS-122: remove outdated link from ZFS primer
  userguide/zfsprimer.rst
Labels: Angulargui, FN/TN

#1682 DOCS-124: Update Services/Rsync text
  userguide/services.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1684 DOCS-119: update translation instructions
  userguide/contribute.rst
Labels: Angulargui, FN/TN
