Repository freenas/freenas-docs, pull requests merged in 2020-03, with the labels that each got.

#1721 DOCS-302: update Exclude Child Datasets field description
  userguide/tasks.rst
Labels: 11.3-U2, FN/TN

#1719 DOCS-291 docs for "enable" in iSCSI extents.
  userguide/sharing.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1724 NAS-104974: Update VFS Objects tables for update ixnas description an…
  userguide/sharing.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1725 NAS-105260: add quick edit to basic dashboard image to show U8.
  userguide/images/tn_webinterface.png
Labels: 11.2-legacy, TrueNAS

#1726 NAS-104998: Synchronize Tasks/Periodic Snapshot Tasks/Add 11.3 UI hel…
  userguide/tasks.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1727 NAS-105113: Update Replication Source and Destination text
  userguide/tasks.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1728 NAS-105110: Add text showing an example of modifying a naming schema.
  userguide/tasks.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1729 NAS-105106 update smb>add options to match UI.
  userguide/sharing.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1730 Update docs for changes to SMB/periodic SS.
  userguide/sharing.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1733 NAS-105425 update SMB docs with Andrew W. feedback.
  userguide/services.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1731 DOCS-353 Update jail upgrading docs.
  userguide/jails.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1732 NAS-105366: update periodic snap tasks: allow taking empty snapshots …
  userguide/tasks.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1734 NAS-105432 Update shadow copy docs with Andrew W. feedback.
  userguide/sharing.rst
Labels: 11.3-U2, Angulargui, FN/TN

#1735 DOCS-252 update api links and fix build error.
  userguide/api.rst
  userguide/tasks.rst
Labels: 11.3-U2, Angulargui, FN/TN
