Repository freenas/freenas-docs, pull requests merged in 2020-02, with the labels that each got.

#1709 DOCS-220: Update Alert Settings docs
  userguide/images/system-alert-settings.png
  userguide/system.rst
Labels: 11.3-U1, Angulargui

#1710 NAS-104977: Screenshot updates for U8
  userguide/images/dashboard.png
  userguide/images/installer-install-menu.png
  userguide/images/save-config.png
  userguide/images/system-update.png
  userguide/images/themes-selector.png
Labels: 11.2-U8, 11.2-angular

#1712 Update copyright year for minimal 11.2-U8 release
  userguide/conf.py
Labels: 11.2-angular

#1713 11.2-U8 legacy UI guide: copyright years
  userguide/conf.py
Labels: 11.2-legacy

#1711 DOCS-282: Reword SSH+Netcat text.
  userguide/tasks.rst
Labels: 11.3-U1

#1714 DOCS-287 docs were there. Just a clarification.
  userguide/sharing.rst
Labels: 11.3-U1, Angulargui, FN/TN

#1708 DOCS-251 add note about changing autotune set values.
  userguide/system.rst
Labels: Angulargui, FN/TN

#1715 DOCS-288 Update field name for AD.
  userguide/directoryservices.rst
Labels: 11.3-U1, Angulargui, FN/TN

#1718 DOCS-290 sync cloudsync field docs with helptext.
  userguide/tasks.rst
Labels: 11.3-U1, Angulargui, FN/TN

#1716 DOCS-289 docs for file browser/ACL tag.
  userguide/snippets/usingui.rst
Labels: 11.3-U1, 12.0, Angulargui, FN/TN

#1720 DOCS-283: Expand docs for Network/IPMI:
  userguide/network.rst
Labels: 11.3-U1, Angulargui, FN/TN

#1722 NAS-104965: Add U1 notes blurb and change version of guide.
  userguide/conf.py
  userguide/intro.rst
Labels: Angulargui

#1723 DOCS-309: Release 11.3-RC1 TrueNAS guide
  userguide/conf.py
Labels: Angulargui, TrueNAS
