Repository freenas/freenas-docs, pull requests merged in 2020-01, with the labels that each got.

#1685 rclone sync delete failures w/ s3 glacier
  userguide/tasks.rst
Labels: Community Contribution

#1687 DOCS-128 Update description of power mode for SMART service.
  userguide/services.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1688 NAS-104563: Add recommendation for disabling SSH "none" cipher.
  userguide/services.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1678 DOCS-87: Create and consolidate VMware information into a new guide s…
  userguide/freenas.rst
  userguide/install.rst
  userguide/sharing.rst
  userguide/truenas.rst
  userguide/vaai.rst
  userguide/vmware.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1690 DOCS-180 add docs for button to API docs in UI.
  userguide/settings.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1691 DOCS-179 doc status column functionality for periodic spapshot tasks.
  userguide/tasks.rst
Labels: 11.3 Release, Angulargui, FN/TN

#1686 Add Amazon S3 docs link to Cloud sync notes.
  userguide/tasks.rst
Labels: Angulargui, FN/TN

#1692 DOCS-185: reset 11.3 guide for RC2 release.
  userguide/conf.py
  userguide/images/console/installer-install-menu.png
  userguide/images/dashboard.png
  userguide/images/system-boot-environments.png
  userguide/images/system-manualupdate.png
  userguide/images/system-support.png
  userguide/images/system-update-staged.png
Labels: 11.3 RC2, Angulargui, FN/TN

#1694 DOCS-126 review all ifdefs for TN. Fixed docs appropriately.
  userguide/directoryservices.rst
  userguide/shell.rst
  userguide/tn_options.rst
  userguide/truenas.rst
Labels: Angulargui, TrueNAS

#1693 DOCS-97: TrueNAS Updates and Trains rework
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1697 DOCS-129: review closed TrueNAS 11.3 tickets and update 11.3 guide
  userguide/conf.py
  userguide/sharing.rst
  userguide/system.rst
Labels: Angulargui, FN/TN

#1698 DOCS-181: Add recommendation about manual snapshot naming to replicat…
  userguide/tasks.rst
Labels: 11.3 RC2, Angulargui, FN/TN

#1699 Update docs for 'use as home share' setting.
  userguide/sharing.rst
Labels: Angulargui, FN/TN

#1700 DOCS-100: Update "Enable Password Login" field description
  userguide/accounts.rst
  userguide/conf.py
Labels: 11.3-RELEASE, Angulargui, FN/TN

#1702 DOCS-130 small docs change for HA review.
  userguide/system.rst
Labels: Angulargui, TrueNAS

#1703 Brand cleanup
  userguide/intro.rst
Labels: Angulargui, FN/TN

#1704 DOCS-202: Rename 11.3 TN guide and add note
  userguide/conf.py
  userguide/tn_intro.rst
Labels: Angulargui, TrueNAS

#1706 DOCS-217 Add sentence bout typing dataset path for rep. tasks.
  userguide/tasks.rst
Labels: 11.3-RELEASE, Angulargui, FN/TN

#1707 Fix syntax error in conf.py TrueNAS PDF version
  userguide/conf.py
Labels: TrueNAS
